#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os 

os.system("clear")

yesil = '\033[92m'
kirmizi = '\033[91m'
beyaz = '\033[37m'
sari = '\033[93m'


print(kirmizi + """
 _______          _     
|__   __|        | |    
   | | ___   ___ | |___ 
   | |/ _ \ / _ \| / __|
   | | (_) | (_) | \___\
   
   |_|\___/ \___/|_|___/ """)    

print(yesil + """    # Coded By wolkan """)


print(beyaz + """
Bu program sizlere siber güvenlikte en çok kullanılan toolları tek tuş ile indirmenizi sağlar. Program süresince indirilen programları kötü amaçlı kullanmayınız. Aksi takdirde kullanılması toplumsal ve hukuki sorumluluk doğurabilir. Olası her durumda mesuliyet ilgili kişiye aittir.""")

print(kirmizi + """\n-----
    |
    v""")
print(beyaz + "    1. Programları İndir\n    2. İndirilecek Olan Programlar")


islem = int(input(beyaz + "\nKullanmak istediğiniz başlığın numarası: "))


if ( islem==1 ):
    os.system("git clone https://github.com/ShuBhamg0sain/Hack_CCTV_Cam-v.3.git")
    os.system("git clone https://github.com/ShuBhamg0sain/trace-ip.git")
    os.system("git clone https://github.com/ShuBhamg0sain/SMSbomber.git")
    os.system("git clone https://github.com/Silent-Blue/Wordlist-Creator.git")
    os.system("git clone https://github.com/ShuBhamg0sain/wifi-passlist.git")
    os.system("git clone https://github.com/ShuBhamg0sain/hack-wifi.git")
    os.system("git clone https://github.com/ShuBhamg0sain/reportbug.git")
    os.system("git clone https://github.com/ShuBhamg0sain/virous.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Locate.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Facebook_hack.git")
    os.system("git clone https://github.com/ShuBhamg0sain/rootkalilinux-termux.git")
    os.system("git clone https://github.com/ShuBhamg0sain/rootubantu-termux.git")
    os.system("git clone https://github.com/ShuBhamg0sain/termux_Arch.git")
    os.system("git clone https://github.com/govolution/avet")
    os.system("git clone https://github.com/ShuBhamg0sain/Facebook-kit.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Fbbrute.git")
    os.system("git clone https://github.com/thewhiteh4t/seeker.git")
    os.system("git clone https://github.com/Findomain/Findomain.git")
    os.system("git clone https://github.com/1aN0rmus/TekDefense-Automater.git")
    os.system("git clone https://github.com/1N3/BruteX.git")
    os.system("git clone https://github.com/1N3/Findsploit.git")
    os.system("git clone https://github.com/1N3/ReverseAPK.git")
    os.system("git clone https://github.com/1N3/Sn1per.git")
    os.system("git clone https://github.com/1tayH/noisy.git")
    os.system("git clone https://github.com/4L13199/LITEDDOS.git")
    os.system("git clone https://github.com/4L13199/LITESPAM.git")
    os.system("git clone https://github.com/4shadoww/hakkuframework.git")
    os.system("git clone https://github.com/4w4k3/BeeLogger.git")
    os.system("git clone https://github.com/4w4k3/KnockMail.git")
    os.system("git clone https://github.com/4w4k3/Umbrella.git")
    os.system("git clone https://github.com/4ZM/mfterm.git")
    os.system("git clone https://github.com/jimywork/djangohunter.git")
    os.system("git clone https://github.com/jimywork/shodanwave.git")
    os.system("git clone https://github.com/a0xnirudh/WebXploiter.git")
    os.system("git clone https://github.com/abaykan/TrackOut.git")
    os.system("git clone https://github.com/abbbe/sslcaudit.git")
    os.system("git clone https://github.com/aboul3la/Sublist3r.git")
    os.system("git clone https://github.com/AeonDave/doork.git")
    os.system("git clone https://github.com/AeonDave/sir.git")
    os.system("git clone https://github.com/anggialberto/xl-py.git")
    os.system("git clone https://github.com/alexxy/netdiscover.git")
    os.system("git clone https://github.com/AlisamTechnology/ATSCAN.git")
    os.system("git clone https://github.com/almandin/fuxploider.git")
    os.system("git clone https://github.com/abaykan/CrawlBox.git")
    os.system("git clone https://github.com/altjx/ipwn.git")
    os.system("git clone https://github.com/andresriancho/w3af.git")
    os.system("git clone https://github.com/AndroBugs/AndroBugs_Framework.git")
    os.system("git clone https://github.com/andyvaikunth/roxysploit.git")
    os.system("git clone https://github.com/AonCyberLabs/PadBuster.git")
    os.system("git clone https://github.com/aquynh/capstone.git")
    os.system("git clone https://github.com/aress31/wirespy.git")
    os.system("git clone https://github.com/arismelachroinos/lscript.git")
    os.system("git clone https://github.com/ASHWIN990/ADB-Toolkit.git")
    os.system("git clone https://github.com/b3-v3r/Hunner.git")
    os.system("git clone https://github.com/BagazMukti/Termux-Styling-Shell-Script.git")
    os.system("git clone https://github.com/bahaabdelwahed/killshot.git")
    os.system("git clone https://github.com/bdblackhat/admin-panel-finder.git")
    os.system("git clone https://github.com/beefproject/beef.git")
    os.system("git clone https://github.com/behindthefirewalls/Parsero.git")
    os.system("git clone https://github.com/bettercap/bettercap.git")
    os.system("git clone https://github.com/bleachbit/bleachbit.git")
    os.system("git clone https://github.com/jofpin/trape.git")
    os.system("git clone https://github.com/byt3bl33d3r/gcat.git")
    os.system("git clone https://github.com/bytezcrew/wfdroid-termux.git")
    os.system("git clone https://github.com/chinoogawa/fbht.git")
    os.system("git clone https://github.com/chrizator/netattack.git")
    os.system("git clone https://github.com/chrizator/netattack2.git")
    os.system("git clone https://github.com/CiKu370/AUXILE.git")
    os.system("git clone https://github.com/CiKu370/hash-generator.git")
    os.system("git clone https://github.com/CiKu370/hasher.git")
    os.system("git clone https://github.com/CiKu370/ko-dork.git")
    os.system("git clone https://github.com/CiKu370/OSIF.git")
    os.system("git clone https://github.com/cinquemb/WifiBruteCrack.git")
    os.system("git clone https://github.com/CISOfy/lynis.git")
    os.system("git clone https://github.com/citronneur/rdpy.git")
    os.system("git clone https://github.com/commixproject/commix.git")
    os.system("git clone https://github.com/cuckoosandbox/cuckoo.git")
    os.system("git clone https://github.com/Cvar1984/Easymap.git")
    os.system("git clone https://github.com/Cvar1984/Ecode.git")
    os.system("git clone https://github.com/Cvar1984/Hac.git")
    os.system("git clone https://github.com/Cvar1984/sqlscan.git")
    os.system("git clone https://github.com/cyberark/shimit.git")
    os.system("git clone https://github.com/cys3c/secHub.git")
    os.system("git clone https://github.com/cyweb/hammer.git")
    os.system("git clone https://github.com/D35m0nd142/Kadabra.git")
    os.system("git clone https://github.com/D35m0nd142/LFISuite.git")
    os.system("git clone https://github.com/D4Vinci/Clickjacking-Tester.git")
    os.system("git clone https://github.com/D4Vinci/Dr0p1t-Framework.git")
    os.system("git clone https://github.com/D4Vinci/elpscrk.git")
    os.system("git clone https://github.com/danielmiessler/SecLists.git")
    os.system("git clone https://github.com/darkoperator/dnsrecon.git")
    os.system("git clone https://github.com/DarkSecDevelopers/HiddenEye-Legacy.git")
    os.system("git clone https://github.com/epsylon/xsser.git")
    os.system("git clone https://github.com/errorBrain/spamchat.git")
    os.system("git clone https://github.com/digininja/CeWL.git")
    os.system("git clone https://github.com/Dionach/CMSmap.git")
    os.system("git clone https://github.com/dotfighter/torshammer.git")
    os.system("git clone https://github.com/EarToEarOak/RTLSDR-Scanner.git")
    os.system("git clone https://github.com/EgeBalci/The-Eye.git")
    os.system("git clone https://github.com/Ekultek/Pybelt.git")
    os.system("git clone https://github.com/EliasOenal/multimon-ng.git")
    os.system("git clone https://github.com/EmpireProject/Empire.git")
    os.system("git clone https://github.com/EnableSecurity/sipvicious.git")
    os.system("git clone https://github.com/EnableSecurity/wafw00f.git")
    os.system("git clone https://github.com/engMaher/BAF.git")
    os.system("git clone https://github.com/epinna/weevely3.git")
    os.system("git clone https://github.com/deadbits/Intersect-2.5.git")
    os.system("git clone https://github.com/derv82/wifite.git")
    os.system("git clone https://github.com/derv82/wifite2.git")
    os.system("git clone https://github.com/esc0rtd3w/wifi-hacker.git")
    os.system("git clone https://github.com/esmog/nodexp.git")
    os.system("git clone https://github.com/evait-security/weeman.git")
    os.system("git clone https://github.com/archival-0x/dedsploit.git")
    os.system("git clone https://github.com/floriankunushevci/rang3r.git")
    os.system("git clone https://github.com/FluxionNetwork/fluxion.git")
    os.system("git clone https://github.com/fnord0/hURL.git")
    os.system("git clone https://github.com/FortyNorthSecurity/EyeWitness.git")
    os.system("git clone https://github.com/fwaeytens/dnsenum.git")
    os.system("git clone https://github.com/g0tmi1k/msfpc.git")
    os.system("git clone https://github.com/galauerscrew/hasherdotid.git")
    os.system("git clone https://github.com/galkan/crowbar.git")
    os.system("git clone https://github.com/Gameye98/AstraNmap.git")
    os.system("git clone https://github.com/Gameye98/Auxscan.git")
    os.system("git clone https://github.com/Gameye98/Black-Hydra.git")
    os.system("git clone https://github.com/Gameye98/FaDe.git")
    os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
    os.system("git clone https://github.com/grafov/hulk.git")
    os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
    os.system("git clone https://github.com/greenbone/openvas-scanner.git")
    os.system("git clone https://github.com/GONZOsint/Namechk.git")
    os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
    os.system("git clone https://github.com/Gameye98/GINF.git")
    os.system("git clone https://github.com/Gameye98/inther.git")
    os.system("git clone https://github.com/Gameye98/Lazymux.git")
    os.system("git clone https://github.com/Gameye98/OWScan.git")
    os.system("git clone https://github.com/Gameye98/santet-online.git")
    os.system("git clone https://github.com/Gameye98/SpazSMS.git")
    os.system("git clone https://github.com/gdabah/distorm.git")
    os.system("git clone https://github.com/GDSSecurity/wifitap.git")
    os.system("git clone https://github.com/geovedi/indonesian-wordlist.git")
    os.system("git clone https://github.com/gitdurandal/dbd.git")
    os.system("git clone https://github.com/GitHackTools/Leaked.git")
    os.system("git clone https://github.com/gkbrk/slowloris.git")
    os.system("git clone https://github.com/golismero/golismero.git")
    os.system("git clone https://github.com/googleinurl/SCANNER-INURLBR.git")
    os.system("git clone https://github.com/grafov/hulk.git")
    os.system("git clone https://github.com/greenbone/openvas.git")
    os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
    os.system("git clone https://github.com/HA71/Namechk.git")
    os.system("git clone https://github.com/hacdias/webdav.git")
    os.system("git clone https://github.com/Hackplayers/4nonimizer.git")
    os.system("git clone https://github.com/the-robot/sqliv.git")
    os.system("git clone https://github.com/hashcat/hashcat.git")
    os.system("git clone https://github.com/hashcat/maskprocessor.git")
    os.system("git clone https://github.com/hatRiot/zarp.git")
    os.system("git clone https://github.com/Hax4us/Metasploit_termux.git")
    os.system("git clone https://github.com/Hax4us/Nethunter-In-Termux.git")
    os.system("git clone https://github.com/Hax4us/TermuxAlpine.git")
    os.system("git clone https://github.com/haxzsadik/MSF-Pg.git")
    os.system("git clone https://github.com/Hood3dRob1n/BinGoo.git")
    os.system("git clone https://github.com/Hydra7/Planetwork-DDOS.git")
    os.system("git clone https://github.com/i3visio/osrframework.git")
    os.system("git clone https://github.com/ihebski/angryFuzzer.git")
    os.system("git clone https://github.com/ikkebr/PyBozoCrack.git")
    os.system("git clone https://github.com/infobyte/faraday.git")
    os.system("git clone https://github.com/iniqua/plecost.git")
    os.system("git clone https://github.com/nccgroup/keimpx.git")
    os.system("git clone https://github.com/iSECPartners/sslyze.git")
    os.system("git clone https://github.com/JamesJGoodwin/wreckuests.git")
    os.system("git clone https://github.com/jaygreig86/dmitry.git")
    os.system("git clone https://github.com/jesparza/peepdf.git")
    os.system("git clone https://github.com/joswr1ght/cowpatty.git")
    os.system("git clone https://github.com/jothatron/blackbox.git")
    os.system("git clone https://github.com/JPaulMora/Pyrit.git")
    os.system("git clone https://github.com/jseidl/GoldenEye.git")
    os.system("git clone https://github.com/k4m4/kickthemout.git")
    os.system("git clone https://github.com/k4m4/onioff.git")
    os.system("git clone https://github.com/kamorin/DHCPig.git")
    os.system("git clone https://github.com/karulis/pybluez.git")
    os.system("git clone https://github.com/KeepWannabe/Remot3d.git")
    os.system("git clone https://github.com/keydet89/RegRipper2.8.git")
    os.system("git clone https://github.com/kgretzky/evilginx2.git")
    os.system("git clone https://github.com/kuburan/txtool.git")
    os.system("git clone https://github.com/LandGrey/pydictor.git")
    os.system("git clone https://github.com/lanmaster53/recon-ng.git")
    os.system("git clone https://github.com/laramies/theHarvester.git")
    os.system("git clone https://github.com/larsbrinkhoff/httptunnel.git")
    os.system("git clone https://github.com/leapsecurity/InSpy.git")
    os.system("git clone https://github.com/lgandx/Responder.git")
    os.system("git clone https://github.com/lightos/credmap.git")
    os.system("git clone https://github.com/linkedin/qark.git")
    os.system("git clone https://github.com/LionSec/wifresti.git")
    os.system("git clone https://github.com/LionSec/xerosploit.git")
    os.system("git clone https://github.com/LOoLzeC/Evil-create-framework.git")
    os.system("git clone https://github.com/LOoLzeC/SH33LL.git")
    os.system("git clone https://github.com/m4ll0k/Infoga.git")
    os.system("git clone https://github.com/m4ll0k/SMBrute.git")
    os.system("git clone https://github.com/m4ll0k/WAScan.git")
    os.system("git clone https://github.com/m4ll0k/WPSeku.git")
    os.system("git clone https://github.com/m4rktn/xsmash.git")
    os.system("git clone https://github.com/m4rktn/zeroeye.git")
    os.system("git clone https://github.com/m8r0wn/subscraper.git")
    os.system("git clone https://github.com/maldevel/IPGeoLocation.git")
    os.system("git clone https://github.com/Manisso/Crips.git")
    os.system("git clone https://github.com/Manisso/Xshell.git")
    os.system("git clone https://github.com/Manisso/fsociety.git")
    os.system("git clone https://github.com/mitmproxy/mitmproxy.git")
    os.system("git clone https://github.com/mnp/xspy.git")
    os.system("git clone https://github.com/Moham3dRiahi/Th3inspector.git")
    os.system("git clone https://github.com/Moham3dRiahi/XAttacker.git")
    os.system("git clone https://github.com/MooseDojo/apt2.git")
    os.system("git clone https://github.com/moxie0/sslstrip.git")
    os.system("git clone https://github.com/moyix/creddump.git")
    os.system("git clone https://github.com/Mr-Un1k0d3r/DKMC.git")
    os.system("git clone https://github.com/Hendriyawan/FBUPv2.0.git")
    os.system("git clone https://github.com/MrSqar-Ye/BadMod.git")
    os.system("git clone https://github.com/mschwager/fierce.git")
    os.system("git clone https://github.com/mteg/braa.git")
    os.system("git clone https://github.com/nathanlopez/Stitch.git")
    os.system("git clone https://github.com/nccgroup/demiguise.git")
    os.system("git clone https://github.com/nccgroup/Winpayloads.git")
    os.system("git clone https://github.com/Neo-Oli/termux-ubuntu.git")
    os.system("git clone https://github.com/Neohapsis/bbqsql.git")
    os.system("git clone https://github.com/neoneggplant/EggShell.git")
    os.system("git clone https://github.com/nfc-tools/mfcuk.git")
    os.system("git clone https://github.com/nfc-tools/mfoc.git")
    os.system("git clone https://github.com/nmilosev/termux-fedora.git")
    os.system("git clone https://github.com/NullArray/AutoSploit.git")
    os.system("git clone https://github.com/nxxxu/AutoPixieWps.git")
    os.system("git clone https://github.com/offensive-security/exploitdb.git")
    os.system("git clone https://github.com/OJ/gobuster.git")
    os.system("git clone https://github.com/orgcandman/Simple-Fuzzer.git")
    os.system("git clone https://github.com/OWASP/OWASP-WebScarab.git")
    os.system("git clone https://github.com/OWASP/QRLJacking.git")
    os.system("git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git")
    os.system("git clone https://github.com/p4kl0nc4t/Spammer-Grab.git")
    os.system("git clone https://github.com/pasahitz/zirikatu.git")
    os.system("git clone https://github.com/peterpt/eternal_scanner.git")
    os.system("git clone https://github.com/peterpt/get.git")
    os.system("git clone https://github.com/portcullislabs/enum4linux.git")
    os.system("git clone https://github.com/PowerScript/KatanaFramework.git")
    os.system("git clone https://github.com/PowerShellMafia/PowerSploit.git")
    os.system("git clone https://github.com/qunxyz/proxystrike.git")
    os.system("git clone https://github.com/r00t-3xp10it/FakeImageExploiter.git")
    os.system("git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL.git")
    os.system("git clone https://github.com/r00t-3xp10it/morpheus.git")
    os.system("git clone https://github.com/r00t-3xp10it/trojanizer.git")
    os.system("git clone https://github.com/r00tmars/ExploitOnCLI.git")
    os.system("git clone https://github.com/r00tmars/XPL-SEARCH.git")
    os.system("git clone https://github.com/Rajkumrdusad/MyServer.git")
    os.system("git clone https://github.com/Rajkumrdusad/Tool-X.git")
    os.system("git clone https://github.com/rand0m1ze/ezsploit.git")
    os.system("git clone https://github.com/ReFirmLabs/binwalk.git")
    os.system("git clone https://github.com/threat9/routersploit.git")
    os.system("git clone https://github.com/reyammer/shellnoob.git")
    os.system("git clone https://github.com/rezasp/joomscan.git")
    os.system("git clone https://github.com/Rhi7/shell-scan.git")
    os.system("git clone https://github.com/ring0lab/catphish.git")
    os.system("git clone https://github.com/riverloopsec/killerbee.git")
    os.system("git clone https://github.com/robertdavidgraham/masscan.git")
    os.system("git clone https://github.com/robertswiecki/intrace.git")
    os.system("git clone https://github.com/ron190/jsql-injection.git")
    os.system("git clone https://github.com/royhills/arp-scan.git")
    os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
    os.system("git clone https://github.com/ruped24/killchain.git")
    os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
    os.system("git clone https://github.com/s0md3v/Blazy.git")
    os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
    os.system("git clone https://github.com/s0md3v/sqlmate.git")
    os.system("git clone https://github.com/s0md3v/Striker.git")
    os.system("git clone https://github.com/s0md3v/XSStrike.git")
    os.system("git clone https://github.com/sabri-zaki/EasY_HaCk.git")
    os.system("git clone https://github.com/samratashok/nishang.git")
    os.system("git clone https://github.com/samyk/pwnat.git")
    os.system("git clone https://github.com/sandalpenyok/kojawafft.git")
    os.system("git clone https://github.com/Sanix-Darker/DDosy.git")
    os.system("git clone https://github.com/savio-code/fern-wifi-cracker.git")
    os.system("git clone https://github.com/savio-code/ghost-phisher.git")
    os.system("git clone https://github.com/Screetsec/Brutal.git")
    os.system("git clone https://github.com/Screetsec/Dracnmap.git")
    os.system("git clone https://github.com/Screetsec/LALIN.git")
    os.system("git clone https://github.com/Screetsec/TheFatRat.git")
    os.system("git clone https://github.com/Screetsec/Vegile.git")
    os.system("git clone https://github.com/secretsquirrel/the-backdoor-factory.git")
    os.system("git clone https://github.com/securestate/termineter.git")
    os.system("git clone https://github.com/sensepost/kwetza.git")
    os.system("git clone https://github.com/shawarkhanethicalhacker/D-TECT-1.git")
    os.system("git clone https://github.com/ShawnDEvans/smbmap.git")
    os.system("git clone https://github.com/shekyan/slowhttptest.git")
    os.system("git clone https://github.com/shinnok/johnny.git")
    os.system("git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git")
    os.system("git clone https://github.com/SilverFoxx/PwnSTAR.git")
    os.system("git clone https://github.com/silverhat007/termux-wordpresscan.git")
    os.system("git clone https://github.com/simsong/bulk_extractor.git")
    os.system("git clone https://github.com/siruidops/uidsploit.git")
    os.system("git clone https://github.com/Smaash/fuckshitup.git")
    os.system("git clone https://github.com/Smaash/snitch.git")
    os.system("git clone https://github.com/Souhardya/Zerodoor.git")
    os.system("git clone https://github.com/SpiderLabs/deblaze.git")
    os.system("git clone https://github.com/SpiderLabs/jboss-autopwn.git")
    os.system("git clone https://github.com/sqlmapproject/sqlmap.git")
    os.system("git clone https://github.com/st42/termux-sudo.git")
    os.system("git clone https://github.com/stamparm/DSSS.git")
    os.system("git clone https://github.com/stamparm/DSVW.git")
    os.system("git clone https://github.com/stamparm/DSXS.git")
    os.system("git clone https://github.com/steve-m/kalibrate-rtl.git")
    os.system("git clone https://github.com/StreetSec/Gloom-Framework.git")
    os.system("git clone https://github.com/sullo/nikto.git")
    os.system("git clone https://github.com/SusmithKrishnan/cpscan.git")
    os.system("git clone https://github.com/SusmithKrishnan/torghost.git")
    os.system("git clone https://github.com/swisskyrepo/Wordpresscan.git")
    os.system("git clone https://github.com/T4P4N/IP-FY.git")
    os.system("git clone https://github.com/t6x/reaver-wps-fork-t6x.git")
    os.system("git clone https://github.com/utkusen/leviathan.git")
    os.system("git clone https://github.com/The404Hacking/websploit.git")
    os.system("git clone https://github.com/thehackingsage/hacktronian.git")
    os.system("git clone https://github.com/ThoughtfulDev/EagleEye.git")
    os.system("git clone https://github.com/tiagorlampert/CHAOS.git")
    os.system("git clone https://github.com/tiagorlampert/sAINT.git")
    os.system("git clone https://github.com/tomac/yersinia.git")
    os.system("git clone https://github.com/trustedsec/ridenum.git")
    os.system("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
    os.system("git clone https://github.com/Tuhinshubhra/CMSeeK.git")
    os.system("git clone https://github.com/Tuhinshubhra/fbvid.git")
    os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK.git")
    os.system("git clone https://github.com/Tuhinshubhra/shellstack.git")
    os.system("git clone https://github.com/Cyb0r9/Androspy.git")
    os.system("git clone https://github.com/Cyb0r9/SocialBox.git")
    os.system("git clone https://github.com/twelvesec/gasmask.git")
    os.system("git clone https://github.com/s0md3v/Breacher.git")
    os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
    os.system("git clone https://github.com/s0md3v/ReconDog.git")
    os.system("git clone https://github.com/s0md3v/sqlmate.git")
    os.system("git clone https://github.com/s0md3v/Striker.git")
    os.system("git clone https://github.com/s0md3v/XSStrike.git")
    os.system("git clone https://github.com/UndeadSec/EvilURL.git")
    os.system("git clone https://github.com/UndeadSec/GoblinWordGenerator.git")
    os.system("git clone https://github.com/UndeadSec/SocialFish.git")
    os.system("git clone https://github.com/urbanadventurer/bing-ip2hosts.git")
    os.system("git clone https://github.com/urbanadventurer/WhatWeb.git")
    os.system("git clone https://github.com/ustayready/CredSniper.git")
    os.system("git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git")
    os.system("git clone https://github.com/vanhauser-thc/thc-ipv6.git")
    os.system("git clone https://github.com/vecna/sniffjoke.git")
    os.system("git clone https://github.com/verluchie/termux-lazysqlmap.git")
    os.system("git clone https://github.com/volatilityfoundation/volatility.git")
    os.system("git clone https://github.com/Wh1t3Rh1n0/air-hammer.git")
    os.system("git clone https://github.com/wifiphisher/wifiphisher.git")
    os.system("git clone https://github.com/wiire-a/pixiewps.git")
    os.system("git clone https://github.com/WiPi-Hunter/PiDense.git")
    os.system("git clone https://github.com/wireghoul/doona.git")
    os.system("git clone https://github.com/wireghoul/dotdotpwn.git")
    os.system("git clone https://github.com/wpscanteam/wpscan.git")
    os.system("git clone https://github.com/x90skysn3k/brutespray.git")
    os.system("git clone https://github.com/xHak9x/fbi.git")
    os.system("git clone https://github.com/Xi4u7/A-Rat.git")
    os.system("git clone https://github.com/xmendez/wfuzz.git")
    os.system("git clone https://github.com/xtr4nge/giskismet.git")
    os.system("git clone https://github.com/Xyl2k/Cookie-stealer.git")
    os.system("git clone https://github.com/Zapotek/cdpsnarf.git")
    os.system("git clone https://github.com/zaproxy/zaproxy.git")
    os.system("git clone https://github.com/zerosum0x0/koadic.git")
    os.system("git clone https://github.com/zigoo0/webpwn3r.git")

elif (islem==2):
    print("\n" + yesil + "zaproxy" + kirmizi + " -----> " + beyaz + "https://github.com/zaproxy/zaproxy")
    print(yesil + "Hack_CCTV_Cam-v.3" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain Hack_CCTV_Cam-v.3")
    print(yesil + "trace-ip" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/trace-ip")
    print(yesil + "SMSbomber" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/SMSbomber")
    print(yesil + "Wordlist-Creator" + kirmizi + " -----> " + beyaz + "https://github.com/Silent-Blue/Wordlist-Creator")
    print(yesil + "wifi-passlist" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/wifi-passlist")
    print(yesil + "hack-wifi" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/hack-wifi")
    print(yesil + "reportbug" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/reportbug")
    print(yesil + "virous" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/virous")
    print(yesil + "Locate" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/Locate")
    print(yesil + "Facebook_hack" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/Facebook_hack")
    print(yesil + "rootkalilinux-termux" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/rootkalilinux-termux")
    print(yesil + "rootubantu-termux" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/rootubantu-termux")
    print(yesil + "termux_Arch" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/termux_Arch")
    print(yesil + "Facebook-kit" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/Facebook-kit")
    print(yesil + "Fbbrute" + kirmizi + " -----> " + beyaz + "https://github.com/ShuBhamg0sain/Fbbrute")
    print(yesil + "seeker" + kirmizi + " -----> " + beyaz + "https://github.com/thewhiteh4t/seeker")
    print(yesil + "Findomain" + kirmizi + " -----> " + beyaz + "https://github.com/Findomain/Findomain")
    print(yesil + "TekDefense-Automater" + kirmizi + " -----> " + beyaz + "https://github.com/1aN0rmus/TekDefense-Automater")
    print(yesil + "BruteX" + kirmizi + " -----> " + beyaz + "https://github.com/1N3/BruteX")
    print(yesil + "Findsploit" + kirmizi + " -----> " + beyaz + "https://github.com/1N3/Findsploit")
    print(yesil + "ReverseAPK" + kirmizi + " -----> " + beyaz + "https://github.com/1N3/ReverseAPK")
    print(yesil + "Sn1per" + kirmizi + " -----> " + beyaz + "https://github.com/1N3/Sn1per")
    print(yesil + "noisy" + kirmizi + " -----> " + beyaz + "https://github.com/1tayH/noisy")
    print(yesil + "LITEDDOS" + kirmizi + " -----> " + beyaz + "https://github.com/4L13199/LITEDDOS")
    print(yesil + "LITESPAM" + kirmizi + " -----> " + beyaz + "https://github.com/4L13199/LITESPAM")
    print(yesil + "hakkuframework" + kirmizi + " -----> " + beyaz + "https://github.com/4shadoww/hakkuframework")
    print(yesil + "BeeLogger" + kirmizi + " -----> " + beyaz + "https://github.com/4w4k3/BeeLogger")
    print(yesil + "KnockMail" + kirmizi + " -----> " + beyaz + "https://github.com/4w4k3/KnockMail")
    print(yesil + "Umbrella" + kirmizi + " -----> " + beyaz + "https://github.com/4w4k3/Umbrella")
    print(yesil + "mfterm" + kirmizi + " -----> " + beyaz + "https://github.com/4ZM/mfterm")
    print(yesil + "djangohunter" + kirmizi + " -----> " + beyaz + "https://github.com/jimywork/djangohunter")
    print(yesil + "shodanwave" + kirmizi + " -----> " + beyaz + "https://github.com/jimywork/shodanwave")
    print(yesil + "WebXploiter" + kirmizi + " -----> " + beyaz + "https://github.com/a0xnirudh/WebXploiter")
    print(yesil + "TrackOut" + kirmizi + " -----> " + beyaz + "https://github.com/abaykan/TrackOut")
    print(yesil + "sslcaudit" + kirmizi + " -----> " + beyaz + "https://github.com/abbbe/sslcaudit")
    print(yesil + "Sublist3r" + kirmizi + " -----> " + beyaz + "https://github.com/aboul3la/Sublist3r")
    print(yesil + "doork" + kirmizi + " -----> " + beyaz + "https://github.com/AeonDave/doork")
    print(yesil + "sir" + kirmizi + " -----> " + beyaz + "https://github.com/AeonDave/sir")
    print(yesil + "xl-py" + kirmizi + " -----> " + beyaz + "https://github.com/anggialberto/xl-py")
    print(yesil + "netdiscover" + kirmizi + " -----> " + beyaz + "https://github.com/alexxy/netdiscover")
    print(yesil + "ATSCAN" + kirmizi + " -----> " + beyaz + "https://github.com/AlisamTechnology/ATSCAN")
    print(yesil + "fuxploider" + kirmizi + " -----> " + beyaz + "https://github.com/almandin/fuxploider")
    print(yesil + "CrawlBox" + kirmizi + " -----> " + beyaz + "https://github.com/abaykan/CrawlBox")
    print(yesil + "ipwn" + kirmizi + " -----> " + beyaz + "https://github.com/altjx/ipwn")
    print(yesil + "avet" + kirmizi + " -----> " + beyaz + "https://github.com/govolution/avet")
    print(yesil + "w3af" + kirmizi + " -----> " + beyaz + "https://github.com/andresriancho/w3af")
    print(yesil + "AndroBugs_Framework" + kirmizi + " -----> " + beyaz + "https://github.com/AndroBugs/AndroBugs_Framework")
    print(yesil + "roxysploit" + kirmizi + " -----> " + beyaz + "https://github.com/andyvaikunth/roxysploit")
    print(yesil + "PadBuster" + kirmizi + " -----> " + beyaz + "https://github.com/AonCyberLabs/PadBuster")
    print(yesil + "capstone" + kirmizi + " -----> " + beyaz + "https://github.com/aquynh/capstone")
    print(yesil + "capstone" + kirmizi + " -----> " + beyaz + "https://github.com/aress31/wirespy")
    print(yesil + "lscript" + kirmizi + " -----> " + beyaz + "https://github.com/arismelachroinos/lscript")
    print(yesil + "ADB-Toolkit" + kirmizi + " -----> " + beyaz + "https://github.com/ASHWIN990/ADB-Toolkit")
    print(yesil + "Hunner" + kirmizi + " -----> " + beyaz + "https://github.com/b3-v3r/Hunner")
    print(yesil + "Termux-Styling-Shell-Script" + kirmizi + " -----> " + beyaz + "https://github.com/BagazMukti/Termux-Styling-Shell-Script")
    print(yesil + "killshot" + kirmizi + " -----> " + beyaz + "https://github.com/bahaabdelwahed/killshot")
    print(yesil + "admin-panel-finder" + kirmizi + " -----> " + beyaz + "https://github.com/bdblackhat/admin-panel-finder")
    print(yesil + "beef" + kirmizi + " -----> " + beyaz + "https://github.com/beefproject/beef")
    print(yesil + "Parsero" + kirmizi + " -----> " + beyaz + "https://github.com/behindthefirewalls/Parsero")
    print(yesil + "bettercap" + kirmizi + " -----> " + beyaz + "https://github.com/bettercap/bettercap")
    print(yesil + "bleachbit" + kirmizi + " -----> " + beyaz + "https://github.com/bleachbit/bleachbit")
    print(yesil + "trape" + kirmizi + " -----> " + beyaz + "https://github.com/jofpin/trape")
    print(yesil + "gcat" + kirmizi + " -----> " + beyaz + "https://github.com/byt3bl33d3r/gcat")
    print(yesil + "wfdroid-termux" + kirmizi + " -----> " + beyaz + "https://github.com/bytezcrew/wfdroid-termux")
    print(yesil + "fbht" + kirmizi + " -----> " + beyaz + "https://github.com/chinoogawa/fbht")
    print(yesil + "netattack" + kirmizi + " -----> " + beyaz + "https://github.com/chrizator/netattack")
    print(yesil + "netattack2" + kirmizi + " -----> " + beyaz + "https://github.com/chrizator/netattack2")
    print(yesil + "AUXILE" +kirmizi + " -----> " + beyaz + "https://github.com/CiKu370/AUXILE")
    print(yesil + "hash-generator" + kirmizi + " -----> " + beyaz + "https://github.com/CiKu370/hash-generator")
    print(yesil + "hasher" + kirmizi + " -----> " + beyaz + "https://github.com/CiKu370/hasher")
    print(yesil + "ko-dork" + kirmizi + " -----> " + beyaz + "https://github.com/CiKu370/ko-dork")
    print(yesil + "OSIF" + kirmizi + " -----> " + beyaz + "https://github.com/CiKu370/OSIF")
    print(yesil + "WifiBruteCrack" + kirmizi + " -----> " + beyaz + "https://github.com/cinquemb/WifiBruteCrack")
    print(yesil + "lynis" + kirmizi + " -----> " + beyaz + "https://github.com/CISOfy/lynis")
    print(yesil + "rdpy" + kirmizi + " -----> " + beyaz + "https://github.com/citronneur/rdpy")
    print(yesil + "commix" + kirmizi + " -----> " + beyaz + "https://github.com/commixproject/commix")
    print(yesil + "cuckoo" + kirmizi + " -----> " + beyaz + "https://github.com/cuckoosandbox/cuckoo")
    print(yesil + "Easymap" + kirmizi + " -----> " + beyaz + "https://github.com/Cvar1984/Easymap")
    print(yesil + "Ecode" + kirmizi + " -----> " + beyaz + "https://github.com/Cvar1984/Ecode")
    print(yesil + "Hac" + kirmizi + " -----> " + beyaz + "https://github.com/Cvar1984/Hac")
    print(yesil + "sqlscan" + kirmizi + " -----> " + beyaz + "https://github.com/Cvar1984/sqlscan")
    print(yesil + "shimit" + kirmizi + " -----> " + beyaz + "https://github.com/cyberark/shimit")
    print(yesil + "secHub" + kirmizi + " -----> " + beyaz + "https://github.com/cys3c/secHub")
    print(yesil + "hammer" + kirmizi + " -----> " + beyaz + "https://github.com/cyweb/hammer")
    print(yesil + "Kadabra" + kirmizi + " -----> " + beyaz + "https://github.com/D35m0nd142/Kadabra")
    print(yesil + "LFISuite" + kirmizi + " -----> " + beyaz + "https://github.com/D35m0nd142/LFISuite")
    print(yesil + "Clickjacking-Tester" + kirmizi + " -----> " + beyaz + "https://github.com/D4Vinci/Clickjacking-Tester")
    print(yesil + "Dr0p1t-Framework" + kirmizi + " -----> " + beyaz + "https://github.com/D4Vinci/Dr0p1t-Framework")
    print(yesil + "elpscrk" + kirmizi + " -----> " + beyaz + "https://github.com/D4Vinci/elpscrk")
    print(yesil + "SecLists" + kirmizi + " -----> " + beyaz + "https://github.com/danielmiessler/SecLists")
    print(yesil + "dnsrecon" + kirmizi + " -----> " + beyaz + "https://github.com/darkoperator/dnsrecon")
    print(yesil + "HiddenEye-Legacy" + kirmizi + " -----> " + beyaz + "https://github.com/DarkSecDevelopers/HiddenEye-Legacy")
    print(yesil + "xsser" + kirmizi + " -----> " + beyaz + "https://github.com/epsylon/xsser")
    print(yesil + "spamchat" + kirmizi + " -----> " + beyaz + "https://github.com/errorBrain/spamchat")
    print(yesil + "CeWL" + kirmizi + " -----> " + beyaz + "https://github.com/digininja/CeWL")
    print(yesil + "CMSmap" + kirmizi + " -----> " + beyaz + "https://github.com/Dionach/CMSmap")
    print(yesil + "torshammer" + kirmizi + " -----> " + beyaz + "https://github.com/dotfighter/torshammer")
    print(yesil + "RTLSDR-Scanner" + kirmizi + " -----> " + beyaz + "https://github.com/EarToEarOak/RTLSDR-Scanner")
    print(yesil + "The-Eye" + kirmizi + " -----> " + beyaz + "https://github.com/EgeBalci/The-Eye")
    print(yesil + "Pybelt" + kirmizi + " -----> " + beyaz + "https://github.com/Ekultek/Pybelt")
    print(yesil + "multimon-ng" + kirmizi + " -----> " + beyaz + "https://github.com/EliasOenal/multimon-ng")
    print(yesil + "Empire" + kirmizi + " -----> " + beyaz + "https://github.com/EmpireProject/Empire")
    print(yesil + "sipvicious" + kirmizi + " -----> " + beyaz + "https://github.com/EnableSecurity/sipvicious")
    print(yesil + "wafw00f" + kirmizi + " -----> " + beyaz + "https://github.com/EnableSecurity/wafw00f")
    print(yesil + "BAF" + kirmizi + " -----> " + beyaz + "https://github.com/engMaher/BAF")
    print(yesil + "weevely3" + kirmizi + " -----> " + beyaz + "https://github.com/epinna/weevely3")
    print(yesil + "Intersect-2" + kirmizi + " -----> " + beyaz + "https://github.com/deadbits/Intersect-2.5")
    print(yesil + "wifite" + kirmizi + " -----> " + beyaz + "https://github.com/derv82/wifite")
    print(yesil + "wifite2" + kirmizi + " -----> " + beyaz + "https://github.com/derv82/wifite2")
    print(yesil + "wifi-hacker" + kirmizi + " -----> " + beyaz + "https://github.com/esc0rtd3w/wifi-hacker")
    print(yesil + "nodexp" + kirmizi + " -----> " + beyaz + "https://github.com/esmog/nodexp")
    print(yesil + "weeman" + kirmizi + " -----> " + beyaz + "https://github.com/evait-security/weeman")
    print(yesil + "dedsploit" + kirmizi + " -----> " + beyaz + "https://github.com/archival-0x/dedsploit")
    print(yesil + "rang3r" + kirmizi + " -----> " + beyaz + "https://github.com/floriankunushevci/rang3r")
    print(yesil + "fluxion" + kirmizi + " -----> " + beyaz + "https://github.com/FluxionNetwork/fluxion")
    print(yesil + "hURL" + kirmizi + " -----> " + beyaz + "https://github.com/fnord0/hURL")
    print(yesil + "EyeWitness" + kirmizi + " -----> " + beyaz + "https://github.com/FortyNorthSecurity/EyeWitness")
    print(yesil + "dnsenum" + kirmizi + " -----> " + beyaz + "https://github.com/fwaeytens/dnsenum")
    print(yesil + "msfpc" + kirmizi + " -----> " + beyaz + "https://github.com/g0tmi1k/msfpc")
    print(yesil + "hasherdotid" + kirmizi + " -----> " + beyaz + "https://github.com/galauerscrew/hasherdotid")
    print(yesil + "crowbar" + kirmizi + " -----> " + beyaz + "https://github.com/galkan/crowbar")
    print(yesil + "AstraNmap" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/AstraNmap")
    print(yesil + "Auxscan" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/Auxscan")
    print(yesil + "Black-Hydra" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/Black-Hydra")
    print(yesil + "FaDe" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/FaDe")
    print(yesil + "hulk" + kirmizi + " -----> " + beyaz + "https://github.com/grafov/hulk")
    print(yesil + "Gemail-Hack" + kirmizi + " -----> " + beyaz + "https://github.com/Ha3MrX/Gemail-Hack")
    print(yesil + "openvas-scanner" + kirmizi + " -----> " + beyaz + "https://github.com/greenbone/openvas-scanner")
    print(yesil + "Namechk" + kirmizi + " -----> " + beyaz + "https://github.com/GONZOsint/Namechk")
    print(yesil + "GoogleSearch-CLI" + kirmizi + " -----> " + beyaz + "https://github.com/BroNils/GoogleSearch-CLI")
    print(yesil + "GINF" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/GINF")
    print(yesil + "inther" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/inther")
    print(yesil + "Lazymux" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/Lazymux")
    print(yesil + "OWScan" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/OWScan")
    print(yesil + "santet-online" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/santet-online")
    print(yesil + "SpazSMS" + kirmizi + " -----> " + beyaz + "https://github.com/Gameye98/SpazSMS")
    print(yesil + "distorm" + kirmizi + " -----> " + beyaz + "https://github.com/gdabah/distorm")
    print(yesil + "wifitap" + kirmizi + " -----> " + beyaz + "https://github.com/GDSSecurity/wifitap")
    print(yesil + "indonesian-wordlist" + kirmizi + " -----> " + beyaz + "https://github.com/geovedi/indonesian-wordlist")
    print(yesil + "dbd" + kirmizi + " -----> " + beyaz + "https://github.com/gitdurandal/dbd")
    print(yesil + "Leaked" + kirmizi + " -----> " + beyaz + "https://github.com/GitHackTools/Leaked")
    print(yesil + "slowloris" + kirmizi + " -----> " + beyaz + "https://github.com/gkbrk/slowloris")
    print(yesil + "golismero" + kirmizi + " -----> " + beyaz + "https://github.com/golismero/golismero")
    print(yesil + "SCANNER-INURLBR" + kirmizi + " -----> " + beyaz + "https://github.com/googleinurl/SCANNER-INURLBR")
    print(yesil + "hulk" + kirmizi + " -----> " + beyaz + "https://github.com/grafov/hulk")
    print(yesil + "openvas" + kirmizi + " -----> " + beyaz + "https://github.com/greenbone/openvas")
    print(yesil + "Gemail-Hack" + kirmizi + " -----> " + beyaz + "https://github.com/Ha3MrX/Gemail-Hack")
    print(yesil + "Namechk" + kirmizi + " -----> " + beyaz + "https://github.com/HA71/Namechk")
    print(yesil + "webdav" + kirmizi + " -----> " + beyaz + "https://github.com/hacdias/webdav")
    print(yesil + "4nonimizer" + kirmizi + " -----> " + beyaz + "https://github.com/Hackplayers/4nonimizer")
    print(yesil + "sqliv" + kirmizi + " -----> " + beyaz + "https://github.com/the-robot/sqliv")
    print(yesil + "hashcat" + kirmizi + " -----> " + beyaz + "https://github.com/hashcat/hashcat")
    print(yesil + "maskprocessor" + kirmizi + " -----> " + beyaz + "https://github.com/hashcat/maskprocessor")
    print(yesil + "zarp" + kirmizi + " -----> " + beyaz + "https://github.com/hatRiot/zarp")
    print(yesil + "Metasploit_termux" + kirmizi + " -----> " + beyaz + "https://github.com/Hax4us/Metasploit_termux")
    print(yesil + "Nethunter-In-Termux" + kirmizi + " -----> " + beyaz + "https://github.com/Hax4us/Nethunter-In-Termux")
    print(yesil + "TermuxAlpine" + kirmizi + " -----> " + beyaz + "https://github.com/Hax4us/TermuxAlpine")
    print(yesil + "MSF-Pg" + kirmizi + " -----> " + beyaz + "https://github.com/haxzsadik/MSF-Pg")
    print(yesil + "BinGoo" + kirmizi + " -----> " + beyaz + "https://github.com/Hood3dRob1n/BinGoo")
    print(yesil + "Planetwork-DDOS" + kirmizi + " -----> " + beyaz + "https://github.com/Hydra7/Planetwork-DDOS")
    print(yesil + "osrframework" + kirmizi + " -----> " + beyaz + "httos://github.com/i3visio/osrframework")
    print(yesil + "angryFuzzer" + kirmizi + " -----> " + beyaz + "https://github.com/ihebski/angryFuzzer")
    print(yesil + "PyBozoCrack" + kirmizi + " -----> " + beyaz + "https://github.com/ikkebr/PyBozoCrack")
    print(yesil + "faraday" + kirmizi + " -----> " + beyaz + "https://github.com/infobyte/faraday")
    print(yesil + "plecost" + kirmizi + " -----> " + beyaz + "https://github.com/iniqua/plecost")
    print(yesil + "keimpx" + kirmizi + " -----> " + beyaz + "https://github.com/nccgroup/keimpx")
    print(yesil + "sslyze" + kirmizi + " -----> " + beyaz + "https://github.com/iSECPartners/sslyze")
    print(yesil + "wreckuests" + kirmizi + " -----> " + beyaz + "https://github.com/JamesJGoodwin/wreckuests")
    print(yesil + "dmitry" + kirmizi + " -----> " + beyaz + "https://github.com/jaygreig86/dmitry")
    print(yesil + "peepdf" + kirmizi + " -----> " + beyaz + "https://github.com/jesparza/peepdf")
    print(yesil + "cowpatty" + kirmizi + " -----> " + beyaz + "https://github.com/joswr1ght/cowpatty")
    print(yesil + "blackbox" + kirmizi + " -----> " + beyaz + "https://github.com/jothatron/blackbox")
    print(yesil + "Pyrit" + kirmizi + " -----> " + beyaz + "https://github.com/JPaulMora/Pyrit")
    print(yesil + "GoldenEye" + kirmizi + " -----> " + beyaz + "https://github.com/jseidl/GoldenEye")
    print(yesil + "kickthemout" + kirmizi + " -----> " + beyaz + "https://github.com/k4m4/kickthemout")
    print(yesil + "onioff" + kirmizi + " -----> " + beyaz + "https://github.com/k4m4/onioff")
    print(yesil + "DHCPig" + kirmizi + " -----> " + beyaz + "https://github.com/kamorin/DHCPig")
    print(yesil + "pybluez" + kirmizi + " -----> " + beyaz + "https://github.com/karulis/pybluez")
    print(yesil + "Remot3d" + kirmizi + " -----> " + beyaz + "https://github.com/KeepWannabe/Remot3d")
    print(yesil + "RegRipper2.8" + kirmizi + " -----> " + beyaz + "https://github.com/keydet89/RegRipper2.8")
    print(yesil + "evilginx2" + kirmizi + " -----> " + beyaz + "https://github.com/kgretzky/evilginx2")
    print(yesil + "txtool" + kirmizi + " -----> " + beyaz + "https://github.com/kuburan/txtool")
    print(yesil + "pydictor" + kirmizi + " -----> " + beyaz + "https://github.com/LandGrey/pydictor")
    print(yesil + "recon-ng" + kirmizi + " -----> " + beyaz + "https://github.com/lanmaster53/recon-ng")
    print(yesil + "theHarvester" + kirmizi + " -----> " + beyaz + "https://github.com/laramies/theHarvester")
    print(yesil + "httptunnel" + kirmizi + " -----> " + beyaz + "https://github.com/larsbrinkhoff/httptunnel")
    print(yesil + "InSpy" + kirmizi + " -----> " + beyaz + "https://github.com/leapsecurity/InSpy")
    print(yesil + "credmap" + kirmizi + " -----> " + beyaz + "https://github.com/lightos/credmap")
    print(yesil + "qark" + kirmizi + " -----> " + beyaz + "https://github.com/linkedin/qark")
    print(yesil + "Responder" + kirmizi + " -----> " + beyaz + "https://github.com/lgandx/Responder")
    print(yesil + "wifresti" + kirmizi + " -----> " + beyaz + "https://github.com/LionSec/wifresti")
    print(yesil + "xerosploit" + kirmizi + " -----> " + beyaz + "https://github.com/LionSec/xerosploit")
    print(yesil + "Evil-create-framework" + kirmizi + " -----> " + beyaz + "https://github.com/LOoLzeC/Evil-create-framework")
    print(yesil + "SH33LL" + kirmizi + " -----> " + beyaz + "https://github.com/LOoLzeC/SH33LL")
    print(yesil + "Infoga" + kirmizi + " -----> " + beyaz + "https://github.com/m4ll0k/Infoga")
    print(yesil + "SMBrute" + kirmizi + " -----> " + beyaz + "https://github.com/m4ll0k/SMBrute")
    print(yesil + "WAScan" + kirmizi + " -----> " + beyaz + "https://github.com/m4ll0k/WAScan")
    print(yesil + "WPSeku" + kirmizi + " -----> " + beyaz + "https://github.com/m4ll0k/WPSeku")
    print(yesil + "xsmash" + kirmizi + " -----> " + beyaz + "https://github.com/m4rktn/xsmash")
    print(yesil + "zeroeye" + kirmizi + " -----> " + beyaz + "https://github.com/m4rktn/zeroeye")
    print(yesil + "subscraper" + kirmizi + " -----> " + beyaz + "https://github.com/m8r0wn/subscraper")
    print(yesil + "IPGeoLocation" + kirmizi + " -----> " + beyaz + "https://github.com/maldevel/IPGeoLocation")
    print(yesil + "Crips" + kirmizi + " -----> " + beyaz + "https://github.com/Manisso/Crips")
    print(yesil + "Xshell" + kirmizi + " -----> " + beyaz + "https://github.com/Manisso/Xshell")
    print(yesil + "fsociety" + kirmizi + " -----> " + beyaz + "https://github.com/Manisso/fsociety")
    print(yesil + "mitmproxy" + kirmizi + " -----> " + beyaz + "https://github.com/mitmproxy/mitmproxy")
    print(yesil + "xspy" + kirmizi + " -----> " + beyaz + "https://github.com/mnp/xspy")
    print(yesil + "Th3inspector" + kirmizi + " -----> " + beyaz + "https://github.com/Moham3dRiahi/Th3inspector")
    print(yesil + "XAttacker" + kirmizi + " -----> " + beyaz + "https://github.com/Moham3dRiahi/XAttacker")
    print(yesil + "apt2" + kirmizi + " -----> " + beyaz + "https://github.com/MooseDojo/apt2")
    print(yesil + "sslstrip" + kirmizi + " -----> " + beyaz + "https://github.com/moxie0/sslstrip")
    print(yesil + "creddump" + kirmizi + " -----> " + beyaz + "https://github.com/moyix/creddump")
    print(yesil + "DKMC" + kirmizi + " -----> " + beyaz + "https://github.com/Mr-Un1k0d3r/DKMC")
    print(yesil + "FBUPv2.0" + kirmizi + " -----> " + beyaz + "https://github.com/Hendriyawan/FBUPv2.0")
    print(yesil + "BadMod" + kirmizi + " -----> " + beyaz + "https://github.com/MrSqar-Ye/BadMod")
    print(yesil + "fierce" + kirmizi + " -----> " + beyaz + "https://github.com/mschwager/fierce")
    print(yesil + "Stitch" + kirmizi + " -----> " + beyaz + "https://github.com/nathanlopez/Stitch")
    print(yesil + "demiguise" + kirmizi + " -----> " + beyaz + "https://github.com/nccgroup/demiguise")
    print(yesil + "Winpayloads" + kirmizi + " -----> " + beyaz + "https://github.com/nccgroup/Winpayloads")
    print(yesil + "termux-ubuntu" + kirmizi + " -----> " + beyaz + "https://github.com/Neo-Oli/termux-ubuntu")
    print(yesil + "bbqsql" + kirmizi + " -----> " + beyaz + "https://github.com/Neohapsis/bbqsql")
    print(yesil + "EggShell" + kirmizi + " -----> " + beyaz + "https://github.com/neoneggplant/EggShell")
    print(yesil + "mfcuk" + kirmizi + " -----> " + beyaz + "https://github.com/nfc-tools/mfcuk")
    print(yesil + "mfoc" + kirmizi + " -----> " + beyaz + "https://github.com/nfc-tools/mfoc")
    print(yesil + "braa" + kirmizi + " -----> " + beyaz + "https://github.com/mteg/braa")
    print(yesil + "termux-fedora" + kirmizi + " -----> " + beyaz + "https://github.com/nmilosev/termux-fedora")
    print(yesil + "AutoSploit" + kirmizi + " -----> " + beyaz + "https://github.com/NullArray/AutoSploit")
    print(yesil + "AutoPixieWps" + kirmizi + " -----> " + beyaz + "https://github.com/nxxxu/AutoPixieWps")
    print(yesil + "exploitdb" + kirmizi + " -----> " + beyaz + "https://github.com/offensive-security/exploitdb")
    print(yesil + "gobuster" + kirmizi + " -----> " + beyaz + "https://github.com/OJ/gobuster")
    print(yesil + "Simple-Fuzzer" + kirmizi + " -----> " + beyaz + "https://github.com/orgcandman/Simple-Fuzzer")
    print(yesil + "OWASP-WebScarab" + kirmizi + " -----> " + beyaz + "https://github.com/OWASP/OWASP-WebScarab")
    print(yesil + "QRLJacking" + kirmizi + " -----> " + beyaz + "https://github.com/OWASP/QRLJacking")
    print(yesil + "WiFi-Pumpkin" + kirmizi + " -----> " + beyaz + "https://github.com/P0cL4bs/WiFi-Pumpkin")
    print(yesil + "Spammer-Grab" + kirmizi + " -----> " + beyaz + "https://github.com/p4kl0nc4t/Spammer-Grab")
    print(yesil + "zirikatu" + kirmizi + " -----> " + beyaz + "https://github.com/pasahitz/zirikatu ")
    print(yesil + "eternal_scanner" + kirmizi + " -----> " + beyaz + "https://github.com/peterpt/eternal_scanner")
    print(yesil + "get" + kirmizi + " -----> " + beyaz + "https://github.com/peterpt/get")
    print(yesil + "enum4linux" + kirmizi + " -----> " + beyaz + "https://github.com/portcullislabs/enum4linux")
    print(yesil + "KatanaFramework" + kirmizi + " -----> " + beyaz + "https://github.com/PowerScript/KatanaFramework")
    print(yesil + "PowerSploit" + kirmizi + " -----> " + beyaz + "https://github.com/PowerShellMafia/PowerSploit")
    print(yesil + "proxystrike" + kirmizi + " -----> " + beyaz + "https://github.com/qunxyz/proxystrike")
    print(yesil + "FakeImageExploiter" + kirmizi + " -----> " + beyaz + "https://github.com/r00t-3xp10it/FakeImageExploiter")
    print(yesil + "Meterpreter_Paranoid_Mode-SSL" + kirmizi + " -----> " + beyaz + "https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL")
    print(yesil + "morpheus" + kirmizi + " -----> " + beyaz + "https://github.com/r00t-3xp10it/morpheus")
    print(yesil + "trojanizer" + kirmizi + " -----> " + beyaz + "https://github.com/r00t-3xp10it/trojanizer")
    print(yesil + "ExploitOnCLI" + kirmizi + " -----> " + beyaz + "https://github.com/r00tmars/ExploitOnCLI")
    print(yesil + "XPL-SEARCH" + kirmizi + " -----> " + beyaz + "https://github.com/r00tmars/XPL-SEARCH")
    print(yesil + "MyServer" + kirmizi + " -----> " + beyaz + "https://github.com/Rajkumrdusad/MyServer")
    print(yesil + "Tool-X" + kirmizi + " -----> " + beyaz + "https://github.com/Rajkumrdusad/Tool-X")
    print(yesil + "ezsploit" + kirmizi + " -----> " + beyaz + "https://github.com/rand0m1ze/ezsploit")
    print(yesil + "binwalk" + kirmizi + " -----> " + beyaz + "https://github.com/ReFirmLabs/binwalk")
    print(yesil + "routersploit" + kirmizi + " -----> " + beyaz + "https://github.com/threat9/routersploit")
    print(yesil + "shellnoob" + kirmizi + " -----> " + beyaz + "https://github.com/reyammer/shellnoob")
    print(yesil + "joomscan" + kirmizi + " -----> " + beyaz + "https://github.com/rezasp/joomscan")
    print(yesil + "shell-scan" + kirmizi + " -----> " + beyaz + "https://github.com/Rhi7/shell-scan")
    print(yesil + "catphish" + kirmizi + " -----> " + beyaz + "https://github.com/ring0lab/catphish")
    print(yesil + "killerbee" + kirmizi + " -----> " + beyaz + "https://github.com/riverloopsec/killerbee")
    print(yesil + "masscan" + kirmizi + " -----> " + beyaz + "https://github.com/robertdavidgraham/masscan")
    print(yesil + "intrace" + kirmizi + " -----> " + beyaz + "https://github.com/robertswiecki/intrace")
    print(yesil + "jsql-injection" + kirmizi + " -----> " + beyaz + "https://github.com/ron190/jsql-injection")
    print(yesil + "arp-scan" + kirmizi + " -----> " + beyaz + "https://github.com/royhills/arp-scan")
    print(yesil + "killchain" + kirmizi + " -----> " + beyaz + "https://github.com/ruped24/killchain")
    print(yesil + "Blazy" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Blazy")
    print(yesil + "Hash-Buster" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Hash-Buster")
    print(yesil + "sqlmate" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/sqlmate")
    print(yesil + "Striker" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Striker")
    print(yesil + "XSStrike" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/XSStrike")
    print(yesil + "EasY_HaCk" + kirmizi + " -----> " + beyaz + "https://github.com/sabri-zaki/EasY_HaCk")
    print(yesil + "nishang" + kirmizi + " -----> " + beyaz + "https://github.com/samratashok/nishang")
    print(yesil + "pwnat" + kirmizi + " -----> " + beyaz + "https://github.com/samyk/pwnat")
    print(yesil + "kojawafft" + kirmizi + " -----> " + beyaz + "https://github.com/sandalpenyok/kojawafft")
    print(yesil + "DDosy" + kirmizi + " -----> " + beyaz + "https://github.com/Sanix-Darker/DDosy")
    print(yesil + "fern-wifi-cracker" + kirmizi + " -----> " + beyaz + "https://github.com/savio-code/fern-wifi-cracker")
    print(yesil + "ghost-phisher" + kirmizi + " -----> " + beyaz + "https://github.com/savio-code/ghost-phisher")
    print(yesil + "Brutal" + kirmizi + " -----> " + beyaz + "https://github.com/Screetsec/Brutal")
    print(yesil + "Dracnmap" + kirmizi + " -----> " + beyaz + "https://github.com/Screetsec/Dracnmap")
    print(yesil + "LALIN" + kirmizi + " -----> " + beyaz + "https://github.com/Screetsec/LALIN")
    print(yesil + "TheFatRat" + kirmizi + " -----> " + beyaz + "https://github.com/Screetsec/TheFatRat")
    print(yesil + "Vegile" + kirmizi + " -----> " + beyaz + "https://github.com/Screetsec/Vegile")
    print(yesil + "the-backdoor-factory" + kirmizi + " -----> " + beyaz + "https://github.com/secretsquirrel/the-backdoor-factory")
    print(yesil + "termineter" + kirmizi + " -----> " + beyaz + "https://github.com/securestate/termineter")
    print(yesil + "kwetza" + kirmizi + " -----> " + beyaz + "https://github.com/sensepost/kwetza")
    print(yesil + "D-TECT-1" + kirmizi + " -----> " + beyaz + "https://github.com/shawarkhanethicalhacker/D-TECT-1")
    print(yesil + "smbmap" + kirmizi + " -----> " + beyaz + "https://github.com/ShawnDEvans/smbmap")
    print(yesil + "slowhttptest" + kirmizi + " -----> " + beyaz + "https://github.com/shekyan/slowhttptest")
    print(yesil + "johnny" + kirmizi + " -----> " + beyaz + "https://github.com/shinnok/johnny")
    print(yesil + "HT-WPS-Breaker" + kirmizi + " -----> " + beyaz + "https://github.com/SilentGhostX/HT-WPS-Breaker")
    print(yesil + "PwnSTAR" + kirmizi + " -----> " + beyaz + "https://github.com/SilverFoxx/PwnSTAR")
    print(yesil + "termux-wordpresscan" + kirmizi + " -----> " + beyaz + "https://github.com/silverhat007/termux-wordpresscan")
    print(yesil + "bulk_extractor" + kirmizi + " -----> " +beyaz + "https://github.com/simsong/bulk_extractor")
    print(yesil + "uidsploit" + kirmizi + " -----> " + beyaz + "https://github.com/siruidops/uidsploit")
    print(yesil + "fuckshitup" + kirmizi + " -----> " + beyaz + "https://github.com/Smaash/fuckshitup")
    print(yesil + "snitch" + kirmizi + " -----> " + beyaz + "https://github.com/Smaash/snitch")
    print(yesil + "Zerodoor" + kirmizi + " -----> " + beyaz + "https://github.com/Souhardya/Zerodoor")
    print(yesil + "deblaze" + kirmizi + " -----> " + beyaz + "https://github.com/SpiderLabs/deblaze")
    print(yesil + "jboss-autopwn" + kirmizi + " -----> " + beyaz + "https://github.com/SpiderLabs/jboss-autopwn")
    print(yesil + "sqlmap" + kirmizi + " -----> " + beyaz + "https://github.com/sqlmapproject/sqlmap")
    print(yesil + "termux-sudo" + kirmizi + " -----> " + beyaz + "https://github.com/st42/termux-sudo")
    print(yesil + "DSSS" + kirmizi + " -----> " + beyaz + "https://github.com/stamparm/DSSS")
    print(yesil + "DSVW" + kirmizi + " -----> " + beyaz + "https://github.com/stamparm/DSVW")
    print(yesil + "DSXS" + kirmizi + " -----> " + beyaz + "https://github.com/stamparm/DSXS")
    print(yesil + "kalibrate-rtl" + kirmizi + " -----> " + beyaz + "https://github.com/steve-m/kalibrate-rtl")
    print(yesil + "Gloom-Framework" + kirmizi + " -----> " + beyaz + "https://github.com/StreetSec/Gloom-Framework")
    print(yesil + "nikto" + kirmizi + " -----> " + beyaz + "https://github.com/sullo/nikto")
    print(yesil + "cpscan" + kirmizi + " -----> " + beyaz + "https://github.com/SusmithKrishnan/cpscan")
    print(yesil + "torghost" + kirmizi + " -----> " + beyaz + "https://github.com/SusmithKrishnan/torghost")
    print(yesil + "Wordpresscan" + kirmizi + " -----> " + beyaz + "https://github.com/swisskyrepo/Wordpresscan")
    print(yesil + "IP-FY" + kirmizi + " -----> " + beyaz+ "https://github.com/T4P4N/IP-FY")
    print(yesil + "reaver-wps-fork-t6x" + kirmizi + " -----> " + beyaz + "https://github.com/t6x/reaver-wps-fork-t6x")
    print(yesil + "leviathan" + kirmizi + " -----> " + beyaz + "https://github.com/utkusen/leviathan")
    print(yesil + "websploit" + kirmizi + " -----> " + beyaz + "https://github.com/The404Hacking/websploit")
    print(yesil + "hacktronian" + kirmizi + " -----> " + beyaz + "https://github.com/thehackingsage/hacktronian")
    print(yesil + "EagleEye" + kirmizi + " -----> " + beyaz + "https://github.com/ThoughtfulDev/EagleEye")
    print(yesil + "CHAOS" + kirmizi + " -----> " + beyaz + "https://github.com/tiagorlampert/CHAOS")
    print(yesil + "sAINT" + kirmizi + " -----> " + beyaz + "https://github.com/tiagorlampert/sAINT")
    print(yesil + "yersinia" + kirmizi + " -----> " + beyaz + "https://github.com/tomac/yersinia")
    print(yesil + "ridenum" + kirmizi + " -----> " + beyaz + "https://github.com/trustedsec/ridenum")
    print(yesil + "social-engineer-toolkit" + kirmizi + " -----> " + beyaz + "https://github.com/trustedsec/social-engineer-toolkit")
    print(yesil + "CMSeeK" + kirmizi + " -----> " + beyaz + "https://github.com/Tuhinshubhra/CMSeeK")
    print(yesil + "fbvid" + kirmizi + " -----> " + beyaz + "https://github.com/Tuhinshubhra/fbvid")
    print(yesil + "RED_HAWK" + kirmizi + " -----> " + beyaz + "https://github.com/Tuhinshubhra/RED_HAWK")
    print(yesil + "shellstack" + kirmizi + " -----> " + beyaz + "https://github.com/Tuhinshubhra/shellstack")
    print(yesil + "Androspy" +kirmizi + " -----> " + beyaz + "https://github.com/Cyb0r9/Androspy")
    print(yesil + "SocialBox" + kirmizi + " -----> " + beyaz + "https://github.com/Cyb0r9/SocialBox")
    print(yesil + "gasmaskprint" + kirmizi + " -----> " + beyaz + "https://github.com/twelvesec/gasmaskprint")
    print(yesil + "Breacher" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Breacher")
    print(yesil + "Hash-Buster" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Hash-Buster")
    print(yesil + "ReconDog" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/ReconDog")
    print(yesil + "sqlmate" + kirmizi+ " -----> " + beyaz + "https://github.com/s0md3v/sqlmate")
    print(yesil + "Striker" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/Striker")
    print(yesil + "XSStrike" + kirmizi + " -----> " + beyaz + "https://github.com/s0md3v/XSStrike")
    print(yesil + "EvilURL" + kirmizi + " -----> " + beyaz + "https://github.com/UndeadSec/EvilURL")
    print(yesil + "GoblinWordGenerator" + kirmizi + " -----> " + beyaz + "https://github.com/UndeadSec/GoblinWordGenerator")
    print(yesil + "SocialFish" + kirmizi + " -----> " + beyaz + "https://github.com/UndeadSec/SocialFish")
    print(yesil + "bing-ip2hosts" +kirmizi + " -----> " + beyaz + "https://github.com/urbanadventurer/bing-ip2hosts")
    print(yesil + "WhatWeb" + kirmizi + " -----> " + beyaz + "https://github.com/urbanadventurer/WhatWeb")
    print(yesil + "CredSniper" + kirmizi + " -----> " + beyaz + "https://github.com/ustayready/CredSniper")
    print(yesil + "airgeddon" + kirmizi + " -----> " + beyaz + "https://github.com/v1s1t0r1sh3r3/airgeddon")
    print(yesil + "thc-ipv6" + kirmizi + " -----> " + beyaz + "https://github.com/vanhauser-thc/thc-ipv6")
    print(yesil + "sniffjoke" + kirmizi + " -----> " + beyaz + "https://github.com/vecna/sniffjoke")
    print(yesil + "termux-lazysqlmap" + kirmizi + " -----> " + beyaz + "https://github.com/verluchie/termux-lazysqlmap")
    print(yesil + "volatility" + kirmizi + " -----> " + beyaz + "https://github.com/volatilityfoundation/volatility")
    print(yesil + "air-hammer" + kirmizi + " -----> " + beyaz + "https://github.com/Wh1t3Rh1n0/air-hammer")
    print(yesil + "wifiphisher" + kirmizi + " -----> " + beyaz + "https://github.com/wifiphisher/wifiphisher")
    print(yesil + "pixiewps" + kirmizi + " -----> " + beyaz + "https://github.com/wiire-a/pixiewps")
    print(yesil + "PiDense" + kirmizi + " -----> " + beyaz + "https://github.com/WiPi-Hunter/PiDense")
    print(yesil + "doona" + kirmizi + " -----> " + beyaz + "https://github.com/wireghoul/doona")
    print(yesil + "dotdotpwn" + kirmizi + " -----> " + beyaz + "https://github.com/wireghoul/dotdotpwn")
    print(yesil + "wpscan" +kirmizi + " -----> " + beyaz + "https://github.com/wpscanteam/wpscan")
    print(yesil + "brutespray" + kirmizi + " -----> " + beyaz + "https://github.com/x90skysn3k/brutespray")
    print(yesil + "fbi" + kirmizi + " -----> " + beyaz + "https://github.com/xHak9x/fbi")
    print(yesil + "A-Rat" +kirmizi + " -----> " + beyaz + "https://github.com/Xi4u7/A-Rat")
    print(yesil + "wfuzz" + kirmizi + " -----> " + beyaz + "https://github.com/xmendez/wfuzz")
    print(yesil + "giskismet" +kirmizi + " -----> " + beyaz + "https://github.com/xtr4nge/giskismet")
    print(yesil + "Cookie-stealer" + kirmizi + " -----> " + beyaz + "https://github.com/Xyl2k/Cookie-stealer")
    print(yesil + "cdpsnarf" + kirmizi + " -----> " + beyaz + "https://github.com/Zapotek/cdpsnarf")
    print(yesil + "zaproxy" + kirmizi + " -----> " + beyaz + "https://github.com/zaproxy/zaproxy")
    print(yesil + "koadic" + kirmizi + " -----> " + beyaz + "https://github.com/zerosum0x0/koadic")
    print(yesil + "webpwn3r" + kirmizi + " -----> " + beyaz + "https://github.com/zigoo0/webpwn3r")
    print("\n" + yesil + "Toplam:" + sari + " 364 Adet Tool İnecektir!" + beyaz)

else:
	print("\nHatalı Karakter Tuşladınız...")
