#!/usr/bin/env python
# -*- coding: utf-8 -*-

import webbrowser
import os 

os.system("clear")


print("""
                                  _______          _     
                                 |__   __|        | |    
                                    | | ___   ___ | |___ 
                                    | |/ _ \ / _ \| / __|
                                    | | (_) | (_) | \___\
	  
	                            |_|\___/ \___/|_|___/ """)    

print("""
                                     # Coded By wolkan """)


print("""
Bu program sizlere siber güvenlikte en çok kullanılan toolları tek tuş ile indirmenizi sağlar. 
Program süresince indirilen programları kötü amaçlı kullanmayınız. Aksi takdirde kullanılması 
toplumsal ve hukuki sorumluluk doğurabilir. Olası her durumda mesuliyet ilgili kişiye aittir.""")

print("""\n-----
    |
    v""")
print("    1. Programları İndir\n    2. İndirilecek Olan Programlar")


islem = int(input("\nKullanmak istediğiniz başlığın numarası: "))


if ( islem==1 ):
    os.system("git clone https://github.com/ShuBhamg0sain/Hack_CCTV_Cam-v.3.git")
    os.system("git clone https://github.com/ShuBhamg0sain/trace-ip.git")
    os.system("git clone https://github.com/ShuBhamg0sain/SMSbomber.git")
    os.system("git clone https://github.com/Silent-Blue/Wordlist-Creator.git")
    os.system("git clone https://github.com/ShuBhamg0sain/wifi-passlist.git")
    os.system("git clone https://github.com/ShuBhamg0sain/hack-wifi.git")
    os.system("git clone https://github.com/ShuBhamg0sain/reportbug.git")
    os.system("git clone https://github.com/ShuBhamg0sain/virous.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Locate.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Facebook_hack.git")
    os.system("git clone https://github.com/ShuBhamg0sain/rootkalilinux-termux.git")
    os.system("git clone https://github.com/ShuBhamg0sain/rootubantu-termux.git")
    os.system("git clone https://github.com/ShuBhamg0sain/termux_Arch.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Facebook-kit.git")
    os.system("git clone https://github.com/ShuBhamg0sain/Fbbrute.git")
    os.system("git clone https://github.com/thewhiteh4t/seeker.git")
    os.system("git clone https://github.com/Findomain/Findomain.git")
    os.system("git clone https://github.com/1aN0rmus/TekDefense-Automater.git")
    os.system("git clone https://github.com/1N3/BruteX.git")
    os.system("git clone https://github.com/1N3/Findsploit.git")
    os.system("git clone https://github.com/1N3/ReverseAPK.git")
    os.system("git clone https://github.com/1N3/Sn1per.git")
    os.system("git clone https://github.com/1tayH/noisy.git")
    os.system("git clone https://github.com/4L13199/LITEDDOS.git")
    os.system("git clone https://github.com/4L13199/LITESPAM.git")
    os.system("git clone https://github.com/4shadoww/hakkuframework.git")
    os.system("git clone https://github.com/4w4k3/BeeLogger.git")    	
    os.system("git clone https://github.com/4w4k3/KnockMail.git")
    os.system("git clone https://github.com/4w4k3/Umbrella.git")
    os.system("git clone https://github.com/4ZM/mfterm.git")
    os.system("git clone https://github.com/jimywork/djangohunter.git")
    os.system("git clone https://github.com/jimywork/shodanwave.git")
    os.system("git clone https://github.com/a0xnirudh/WebXploiter.git")
    os.system("git clone https://github.com/abaykan/TrackOut.git")
    os.system("git clone https://github.com/abbbe/sslcaudit.git")
    os.system("git clone https://github.com/aboul3la/Sublist3r.git")
    os.system("git clone https://github.com/AeonDave/doork.git")
    os.system("git clone https://github.com/AeonDave/sir.git")
    os.system("git clone https://github.com/anggialberto/xl-py.git")
    os.system("git clone https://github.com/alexxy/netdiscover.git")
    os.system("git clone https://github.com/AlisamTechnology/ATSCAN.git")
    os.system("git clone https://github.com/almandin/fuxploider.git")
    os.system("git clone https://github.com/abaykan/CrawlBox.git")
    os.system("git clone https://github.com/altjx/ipwn.git")
    os.system("git clone https://github.com/andresriancho/w3af.git")
    os.system("git clone https://github.com/AndroBugs/AndroBugs_Framework.git")
    os.system("git clone https://github.com/andyvaikunth/roxysploit.git")
    os.system("git clone https://github.com/AonCyberLabs/PadBuster.git")
    os.system("git clone https://github.com/aquynh/capstone.git")
    os.system("git clone https://github.com/aress31/wirespy.git")
    os.system("git clone https://github.com/arismelachroinos/lscript.git")
    os.system("git clone https://github.com/ASHWIN990/ADB-Toolkit.git")
    os.system("git clone https://github.com/b3-v3r/Hunner.git")
    os.system("git clone https://github.com/BagazMukti/Termux-Styling-Shell-Script.git")
    os.system("git clone https://github.com/bahaabdelwahed/killshot.git")
    os.system("git clone https://github.com/bdblackhat/admin-panel-finder.git")
    os.system("git clone https://github.com/beefproject/beef.git")
    os.system("git clone https://github.com/behindthefirewalls/Parsero.git")
    os.system("git clone https://github.com/bettercap/bettercap.git")
    os.system("git clone https://github.com/bleachbit/bleachbit.git")
    os.system("git clone https://github.com/jofpin/trape.git")
    os.system("git clone https://github.com/byt3bl33d3r/gcat.git")
    os.system("git clone https://github.com/bytezcrew/wfdroid-termux.git")
    os.system("git clone https://github.com/chinoogawa/fbht.git")
    os.system("git clone https://github.com/chrizator/netattack.git")
    os.system("git clone https://github.com/chrizator/netattack2.git")
    os.system("git clone https://github.com/CiKu370/AUXILE.git")
    os.system("git clone https://github.com/CiKu370/hash-generator.git")
    os.system("git clone https://github.com/CiKu370/hasher.git")
    os.system("git clone https://github.com/CiKu370/ko-dork.git")
    os.system("git clone https://github.com/CiKu370/OSIF.git")
    os.system("git clone https://github.com/cinquemb/WifiBruteCrack.git")
    os.system("git clone https://github.com/CISOfy/lynis.git")
    os.system("git clone https://github.com/citronneur/rdpy.git")
    os.system("git clone https://github.com/commixproject/commix.git")
    os.system("git clone https://github.com/cuckoosandbox/cuckoo.git")
    os.system("git clone https://github.com/Cvar1984/Easymap.git")
    os.system("git clone https://github.com/Cvar1984/Ecode.git")
    os.system("git clone https://github.com/Cvar1984/Hac.git")
    os.system("git clone https://github.com/Cvar1984/sqlscan.git")
    os.system("git clone https://github.com/cyberark/shimit.git")
    os.system("git clone https://github.com/cys3c/secHub.git")
    os.system("git clone https://github.com/cyweb/hammer.git")
    os.system("git clone https://github.com/D35m0nd142/Kadabra.git")
    os.system("git clone https://github.com/D35m0nd142/LFISuite.git")
    os.system("git clone https://github.com/D4Vinci/Clickjacking-Tester.git")
    os.system("git clone https://github.com/D4Vinci/Dr0p1t-Framework.git")
    os.system("git clone https://github.com/D4Vinci/elpscrk.git")
    os.system("git clone https://github.com/danielmiessler/SecLists.git")
    os.system("git clone https://github.com/darkoperator/dnsrecon.git")
    os.system("git clone https://github.com/DarkSecDevelopers/HiddenEye-Legacy.git")
    os.system("git clone https://github.com/epsylon/xsser.git")
    os.system("git clone https://github.com/errorBrain/spamchat.git")
    os.system("git clone https://github.com/digininja/CeWL.git")
    os.system("git clone https://github.com/Dionach/CMSmap.git")
    os.system("git clone https://github.com/dotfighter/torshammer.git")
    os.system("git clone https://github.com/EarToEarOak/RTLSDR-Scanner.git")
    os.system("git clone https://github.com/EgeBalci/The-Eye.git")
    os.system("git clone https://github.com/Ekultek/Pybelt.git")
    os.system("git clone https://github.com/EliasOenal/multimon-ng.git")
    os.system("git clone https://github.com/EmpireProject/Empire.git")
    os.system("git clone https://github.com/EnableSecurity/sipvicious.git")
    os.system("git clone https://github.com/EnableSecurity/wafw00f.git")
    os.system("git clone https://github.com/engMaher/BAF.git")
    os.system("git clone https://github.com/epinna/weevely3.git")
    os.system("git clone https://github.com/deadbits/Intersect-2.5.git")
    os.system("git clone https://github.com/derv82/wifite.git")
    os.system("git clone https://github.com/derv82/wifite2.git")
    os.system("git clone https://github.com/esc0rtd3w/wifi-hacker.git")
    os.system("git clone https://github.com/esmog/nodexp.git")
    os.system("git clone https://github.com/evait-security/weeman.git")
    os.system("git clone https://github.com/archival-0x/dedsploit.git")
    os.system("git clone https://github.com/floriankunushevci/rang3r.git")
    os.system("git clone https://github.com/FluxionNetwork/fluxion.git")
    os.system("git clone https://github.com/fnord0/hURL.git")
    os.system("git clone https://github.com/FortyNorthSecurity/EyeWitness.git")
    os.system("git clone https://github.com/fwaeytens/dnsenum.git")
    os.system("git clone https://github.com/g0tmi1k/msfpc.git")
    os.system("git clone https://github.com/galauerscrew/hasherdotid.git")
    os.system("git clone https://github.com/galkan/crowbar.git")
    os.system("git clone https://github.com/Gameye98/AstraNmap.git")
    os.system("git clone https://github.com/Gameye98/Auxscan.git")
    os.system("git clone https://github.com/Gameye98/Black-Hydra.git")
    os.system("git clone https://github.com/Gameye98/FaDe.git")
    os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
    os.system("git clone https://github.com/grafov/hulk.git")
    os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
    os.system("git clone https://github.com/greenbone/openvas-scanner.git")
    os.system("git clone https://github.com/GONZOsint/Namechk.git")
    os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
    os.system("git clone https://github.com/Gameye98/GINF.git")
    os.system("git clone https://github.com/Gameye98/inther.git")
    os.system("git clone https://github.com/Gameye98/Lazymux.git")
    os.system("git clone https://github.com/Gameye98/OWScan.git")
    os.system("git clone https://github.com/Gameye98/santet-online.git")
    os.system("git clone https://github.com/Gameye98/SpazSMS.git")
    os.system("git clone https://github.com/gdabah/distorm.git")
    os.system("git clone https://github.com/GDSSecurity/wifitap.git")
    os.system("git clone https://github.com/geovedi/indonesian-wordlist.git")
    os.system("git clone https://github.com/gitdurandal/dbd.git")
    os.system("git clone https://github.com/GitHackTools/Leaked.git")
    os.system("git clone https://github.com/gkbrk/slowloris.git")
    os.system("git clone https://github.com/golismero/golismero.git")
    os.system("git clone https://github.com/googleinurl/SCANNER-INURLBR.git")
    os.system("git clone https://github.com/grafov/hulk.git")
    os.system("git clone https://github.com/greenbone/openvas.git")
    os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
    os.system("git clone https://github.com/HA71/Namechk.git")
    os.system("git clone https://github.com/hacdias/webdav.git")
    os.system("git clone https://github.com/Hackplayers/4nonimizer.git")
    os.system("git clone https://github.com/the-robot/sqliv.git")
    os.system("git clone https://github.com/hashcat/hashcat.git")
    os.system("git clone https://github.com/hashcat/maskprocessor.git")
    os.system("git clone https://github.com/hatRiot/zarp.git")
    os.system("git clone https://github.com/Hax4us/Metasploit_termux.git")
    os.system("git clone https://github.com/Hax4us/Nethunter-In-Termux.git")
    os.system("git clone https://github.com/Hax4us/TermuxAlpine.git")
    os.system("git clone https://github.com/haxzsadik/MSF-Pg.git")
    os.system("git clone https://github.com/Hood3dRob1n/BinGoo.git")
    os.system("git clone https://github.com/Hydra7/Planetwork-DDOS.git")
    os.system("git clone https://github.com/i3visio/osrframework.git")
    os.system("git clone https://github.com/ihebski/angryFuzzer.git")
    os.system("git clone https://github.com/ikkebr/PyBozoCrack.git")
    os.system("git clone https://github.com/infobyte/faraday.git")
    os.system("git clone https://github.com/iniqua/plecost.git")
    os.system("git clone https://github.com/nccgroup/keimpx.git")
    os.system("git clone https://github.com/iSECPartners/sslyze.git")
    os.system("git clone https://github.com/JamesJGoodwin/wreckuests.git")
    os.system("git clone https://github.com/jaygreig86/dmitry.git")
    os.system("git clone https://github.com/jesparza/peepdf.git")
    os.system("git clone https://github.com/joswr1ght/cowpatty.git")
    os.system("git clone https://github.com/jothatron/blackbox.git")
    os.system("git clone https://github.com/JPaulMora/Pyrit.git")
    os.system("git clone https://github.com/jseidl/GoldenEye.git")
    os.system("git clone https://github.com/k4m4/kickthemout.git")
    os.system("git clone https://github.com/k4m4/onioff.git")
    os.system("git clone https://github.com/kamorin/DHCPig.git")
    os.system("git clone https://github.com/karulis/pybluez.git")
    os.system("git clone https://github.com/KeepWannabe/Remot3d.git")
    os.system("git clone https://github.com/keydet89/RegRipper2.8.git")
    os.system("git clone https://github.com/kgretzky/evilginx2.git")
    os.system("git clone https://github.com/kuburan/txtool.git")
    os.system("git clone https://github.com/LandGrey/pydictor.git")
    os.system("git clone https://github.com/lanmaster53/recon-ng.git")
    os.system("git clone https://github.com/laramies/theHarvester.git")
    os.system("git clone https://github.com/larsbrinkhoff/httptunnel.git")
    os.system("git clone https://github.com/leapsecurity/InSpy.git")
    os.system("git clone https://github.com/lgandx/Responder.git")
    os.system("git clone https://github.com/lightos/credmap.git")
    os.system("git clone https://github.com/linkedin/qark.git")
    os.system("git clone https://github.com/LionSec/wifresti.git")
    os.system("git clone https://github.com/LionSec/xerosploit.git")
    os.system("git clone https://github.com/LOoLzeC/Evil-create-framework.git")
    os.system("git clone https://github.com/LOoLzeC/SH33LL.git")
    os.system("git clone https://github.com/m4ll0k/Infoga.git")
    os.system("git clone https://github.com/m4ll0k/SMBrute.git")
    os.system("git clone https://github.com/m4ll0k/WAScan.git")
    os.system("git clone https://github.com/m4ll0k/WPSeku.git")
    os.system("git clone https://github.com/m4rktn/xsmash.git")
    os.system("git clone https://github.com/m4rktn/zeroeye.git")
    os.system("git clone https://github.com/m8r0wn/subscraper.git")
    os.system("git clone https://github.com/maldevel/IPGeoLocation.git")
    os.system("git clone https://github.com/Manisso/Crips.git")
    os.system("git clone https://github.com/Manisso/Xshell.git")
    os.system("git clone https://github.com/Manisso/fsociety.git")
    os.system("git clone https://github.com/mitmproxy/mitmproxy.git")
    os.system("git clone https://github.com/mnp/xspy.git")
    os.system("git clone https://github.com/Moham3dRiahi/Th3inspector.git")
    os.system("git clone https://github.com/Moham3dRiahi/XAttacker.git")
    os.system("git clone https://github.com/MooseDojo/apt2.git")
    os.system("git clone https://github.com/moxie0/sslstrip.git")
    os.system("git clone https://github.com/moyix/creddump.git")
    os.system("git clone https://github.com/Mr-Un1k0d3r/DKMC.git")
    os.system("git clone https://github.com/Hendriyawan/FBUPv2.0.git")
    os.system("git clone https://github.com/MrSqar-Ye/BadMod.git")
    os.system("git clone https://github.com/mschwager/fierce.git")
    os.system("git clone https://github.com/mteg/braa.git")
    os.system("git clone https://github.com/nathanlopez/Stitch.git")
    os.system("git clone https://github.com/nccgroup/demiguise.git")
    os.system("git clone https://github.com/nccgroup/Winpayloads.git")
    os.system("git clone https://github.com/Neo-Oli/termux-ubuntu.git")
    os.system("git clone https://github.com/Neohapsis/bbqsql.git")
    os.system("git clone https://github.com/neoneggplant/EggShell.git")
    os.system("git clone https://github.com/nfc-tools/mfcuk.git")
    os.system("git clone https://github.com/nfc-tools/mfoc.git")
    os.system("git clone https://github.com/nmilosev/termux-fedora.git")
    os.system("git clone https://github.com/NullArray/AutoSploit.git")
    os.system("git clone https://github.com/nxxxu/AutoPixieWps.git")
    os.system("git clone https://github.com/offensive-security/exploitdb.git")
    os.system("git clone https://github.com/OJ/gobuster.git")
    os.system("git clone https://github.com/orgcandman/Simple-Fuzzer.git")
    os.system("git clone https://github.com/OWASP/OWASP-WebScarab.git")
    os.system("git clone https://github.com/OWASP/QRLJacking.git")
    os.system("git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git")
    os.system("git clone https://github.com/p4kl0nc4t/Spammer-Grab.git")
    os.system("git clone https://github.com/pasahitz/zirikatu.git")
    os.system("git clone https://github.com/peterpt/eternal_scanner.git")
    os.system("git clone https://github.com/peterpt/get.git")
    os.system("git clone https://github.com/portcullislabs/enum4linux.git")
    os.system("git clone https://github.com/PowerScript/KatanaFramework.git")
    os.system("git clone https://github.com/PowerShellMafia/PowerSploit.git")
    os.system("git clone https://github.com/qunxyz/proxystrike.git")
    os.system("git clone https://github.com/r00t-3xp10it/FakeImageExploiter.git")
    os.system("git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL.git")
    os.system("git clone https://github.com/r00t-3xp10it/morpheus.git")
    os.system("git clone https://github.com/r00t-3xp10it/trojanizer.git")
    os.system("git clone https://github.com/r00tmars/ExploitOnCLI.git")
    os.system("git clone https://github.com/r00tmars/XPL-SEARCH.git")
    os.system("git clone https://github.com/Rajkumrdusad/MyServer.git")
    os.system("git clone https://github.com/Rajkumrdusad/Tool-X.git")
    os.system("git clone https://github.com/rand0m1ze/ezsploit.git")
    os.system("git clone https://github.com/ReFirmLabs/binwalk.git")
    os.system("git clone https://github.com/threat9/routersploit.git")
    os.system("git clone https://github.com/reyammer/shellnoob.git")
    os.system("git clone https://github.com/rezasp/joomscan.git")
    os.system("git clone https://github.com/Rhi7/shell-scan.git")
    os.system("git clone https://github.com/ring0lab/catphish.git")
    os.system("git clone https://github.com/riverloopsec/killerbee.git")
    os.system("git clone https://github.com/robertdavidgraham/masscan.git")
    os.system("git clone https://github.com/robertswiecki/intrace.git")
    os.system("git clone https://github.com/ron190/jsql-injection.git")
    os.system("git clone https://github.com/royhills/arp-scan.git")
    os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
    os.system("git clone https://github.com/ruped24/killchain.git")
    os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
    os.system("git clone https://github.com/s0md3v/Blazy.git")
    os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
    os.system("git clone https://github.com/s0md3v/sqlmate.git")
    os.system("git clone https://github.com/s0md3v/Striker.git")
    os.system("git clone https://github.com/s0md3v/XSStrike.git")
    os.system("git clone https://github.com/sabri-zaki/EasY_HaCk.git")
    os.system("git clone https://github.com/samratashok/nishang.git")
    os.system("git clone https://github.com/samyk/pwnat.git")
    os.system("git clone https://github.com/sandalpenyok/kojawafft.git")
    os.system("git clone https://github.com/Sanix-Darker/DDosy.git")
    os.system("git clone https://github.com/savio-code/fern-wifi-cracker.git")
    os.system("git clone https://github.com/savio-code/ghost-phisher.git")
    os.system("git clone https://github.com/Screetsec/Brutal.git")
    os.system("git clone https://github.com/Screetsec/Dracnmap.git")
    os.system("git clone https://github.com/Screetsec/LALIN.git")
    os.system("git clone https://github.com/Screetsec/TheFatRat.git")
    os.system("git clone https://github.com/Screetsec/Vegile.git")
    os.system("git clone https://github.com/secretsquirrel/the-backdoor-factory.git")
    os.system("git clone https://github.com/securestate/termineter.git")
    os.system("git clone https://github.com/sensepost/kwetza.git")
    os.system("git clone https://github.com/shawarkhanethicalhacker/D-TECT-1.git")
    os.system("git clone https://github.com/ShawnDEvans/smbmap.git")
    os.system("git clone https://github.com/shekyan/slowhttptest.git")
    os.system("git clone https://github.com/shinnok/johnny.git")
    os.system("git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git")
    os.system("git clone https://github.com/SilverFoxx/PwnSTAR.git")
    os.system("git clone https://github.com/silverhat007/termux-wordpresscan.git")
    os.system("git clone https://github.com/simsong/bulk_extractor.git")
    os.system("git clone https://github.com/siruidops/uidsploit.git")
    os.system("git clone https://github.com/Smaash/fuckshitup.git")
    os.system("git clone https://github.com/Smaash/snitch.git")
    os.system("git clone https://github.com/Souhardya/Zerodoor.git")
    os.system("git clone https://github.com/SpiderLabs/deblaze.git")
    os.system("git clone https://github.com/SpiderLabs/jboss-autopwn.git")
    os.system("git clone https://github.com/sqlmapproject/sqlmap.git")
    os.system("git clone https://github.com/st42/termux-sudo.git")
    os.system("git clone https://github.com/stamparm/DSSS.git")
    os.system("git clone https://github.com/stamparm/DSVW.git")
    os.system("git clone https://github.com/stamparm/DSXS.git")
    os.system("git clone https://github.com/steve-m/kalibrate-rtl.git")
    os.system("git clone https://github.com/StreetSec/Gloom-Framework.git")
    os.system("git clone https://github.com/sullo/nikto.git")
    os.system("git clone https://github.com/SusmithKrishnan/cpscan.git")
    os.system("git clone https://github.com/SusmithKrishnan/torghost.git")
    os.system("git clone https://github.com/swisskyrepo/Wordpresscan.git")
    os.system("git clone https://github.com/T4P4N/IP-FY.git")
    os.system("git clone https://github.com/t6x/reaver-wps-fork-t6x.git")
    os.system("git clone https://github.com/utkusen/leviathan.git")
    os.system("git clone https://github.com/The404Hacking/websploit.git")
    os.system("git clone https://github.com/thehackingsage/hacktronian.git")
    os.system("git clone https://github.com/ThoughtfulDev/EagleEye.git")
    os.system("git clone https://github.com/tiagorlampert/CHAOS.git")
    os.system("git clone https://github.com/tiagorlampert/sAINT.git")
    os.system("git clone https://github.com/tomac/yersinia.git")
    os.system("git clone https://github.com/trustedsec/ridenum.git")
    os.system("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
    os.system("git clone https://github.com/Tuhinshubhra/CMSeeK.git")
    os.system("git clone https://github.com/Tuhinshubhra/fbvid.git")
    os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK.git")
    os.system("git clone https://github.com/Tuhinshubhra/shellstack.git")
    os.system("git clone https://github.com/Cyb0r9/Androspy.git")
    os.system("git clone https://github.com/Cyb0r9/SocialBox.git")
    os.system("git clone https://github.com/twelvesec/gasmask.git")
    os.system("git clone https://github.com/s0md3v/Breacher.git")
    os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
    os.system("git clone https://github.com/s0md3v/ReconDog.git")
    os.system("git clone https://github.com/s0md3v/sqlmate.git")
    os.system("git clone https://github.com/s0md3v/Striker.git")
    os.system("git clone https://github.com/s0md3v/XSStrike.git")
    os.system("git clone https://github.com/UndeadSec/EvilURL.git")
    os.system("git clone https://github.com/UndeadSec/GoblinWordGenerator.git")
    os.system("git clone https://github.com/UndeadSec/SocialFish.git")
    os.system("git clone https://github.com/urbanadventurer/bing-ip2hosts.git")
    os.system("git clone https://github.com/urbanadventurer/WhatWeb.git")
    os.system("git clone https://github.com/ustayready/CredSniper.git")
    os.system("git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git")
    os.system("git clone https://github.com/vanhauser-thc/thc-ipv6.git")
    os.system("git clone https://github.com/vecna/sniffjoke.git")
    os.system("git clone https://github.com/verluchie/termux-lazysqlmap.git")
    os.system("git clone https://github.com/volatilityfoundation/volatility.git")
    os.system("git clone https://github.com/Wh1t3Rh1n0/air-hammer.git")
    os.system("git clone https://github.com/wifiphisher/wifiphisher.git")
    os.system("git clone https://github.com/wiire-a/pixiewps.git")
    os.system("git clone https://github.com/WiPi-Hunter/PiDense.git")
    os.system("git clone https://github.com/wireghoul/doona.git")		
    os.system("git clone https://github.com/wireghoul/dotdotpwn.git")
    os.system("git clone https://github.com/wpscanteam/wpscan.git")
    os.system("git clone https://github.com/x90skysn3k/brutespray.git")
    os.system("git clone https://github.com/xHak9x/fbi.git")
    os.system("git clone https://github.com/Xi4u7/A-Rat.git")
    os.system("git clone https://github.com/xmendez/wfuzz.git")
    os.system("git clone https://github.com/xtr4nge/giskismet.git")
    os.system("git clone https://github.com/Xyl2k/Cookie-stealer.git")
    os.system("git clone https://github.com/Zapotek/cdpsnarf.git")
    os.system("git clone https://github.com/zaproxy/zaproxy.git")
    os.system("git clone https://github.com/zerosum0x0/koadic.git")
    os.system("git clone https://github.com/zigoo0/webpwn3r.git")

elif (islem==2):
    print("\n" + "zaproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zaproxy/zaproxy")
    print("Hack_CCTV_Cam-v.3" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain Hack_CCTV_Cam-v.3")
    print("trace-ip" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/trace-ip")
    print("SMSbomber" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/SMSbomber")
    print("Wordlist-Creator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Silent-Blue/Wordlist-Creator")
    print("wifi-passlist" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/wifi-passlist")
    print("hack-wifi" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/hack-wifi")
    print("reportbug" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/reportbug")
    print("virous" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/virous")
    print("Locate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Locate")
    print("Facebook_hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Facebook_hack")
    print("rootkalilinux-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/rootkalilinux-termux")
    print("rootubantu-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/rootubantu-termux")
    print("termux_Arch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/termux_Arch")
    print("Facebook-kit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Facebook-kit")
    print("Fbbrute" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Fbbrute")
    print("seeker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/thewhiteh4t/seeker")
    print("Findomain" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Findomain/Findomain")
    print("TekDefense-Automater" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1aN0rmus/TekDefense-Automater")
    print("BruteX" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/BruteX")
    print("Findsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/Findsploit")
    print("ReverseAPK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/ReverseAPK")
    print("Sn1per" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/Sn1per")
    print("noisy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1tayH/noisy")
    print("LITEDDOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4L13199/LITEDDOS")
    print("LITESPAM" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4L13199/LITESPAM")
    print("hakkuframework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4shadoww/hakkuframework")
    print("BeeLogger" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/BeeLogger")
    print("KnockMail" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/KnockMail")
    print("Umbrella" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/Umbrella")
    print("mfterm" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4ZM/mfterm")
    print("djangohunter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jimywork/djangohunter")
    print("shodanwave" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jimywork/shodanwave")
    print("WebXploiter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/a0xnirudh/WebXploiter")
    print("TrackOut" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abaykan/TrackOut")
    print("sslcaudit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abbbe/sslcaudit")
    print("Sublist3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aboul3la/Sublist3r")
    print("doork" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AeonDave/doork")
    print("sir" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AeonDave/sir")
    print("xl-py" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/anggialberto/xl-py")
    print("netdiscover" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/alexxy/netdiscover")
    print("ATSCAN" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AlisamTechnology/ATSCAN")
    print("fuxploider" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/almandin/fuxploider")
    print("CrawlBox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abaykan/CrawlBox")
    print("ipwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/altjx/ipwn")
    print("w3af" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/andresriancho/w3af")
    print("AndroBugs_Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AndroBugs/AndroBugs_Framework")
    print("roxysploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/andyvaikunth/roxysploit")
    print("PadBuster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AonCyberLabs/PadBuster")
    print("capstone" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aquynh/capstone")
    print("capstone" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aress31/wirespy")
    print("lscript" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/arismelachroinos/lscript")
    print("ADB-Toolkit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ASHWIN990/ADB-Toolkit")
    print("Hunner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/b3-v3r/Hunner")
    print("Termux-Styling-Shell-Script" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/BagazMukti/Termux-Styling-Shell-Script")
    print("killshot" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bahaabdelwahed/killshot")
    print("admin-panel-finder" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bdblackhat/admin-panel-finder")
    print("beef" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/beefproject/beef")
    print("Parsero" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/behindthefirewalls/Parsero")
    print("bettercap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bettercap/bettercap")
    print("bleachbit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bleachbit/bleachbit")
    print("trape" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jofpin/trape")
    print("gcat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/byt3bl33d3r/gcat")
    print("wfdroid-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bytezcrew/wfdroid-termux")
    print("fbht" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chinoogawa/fbht")
    print("netattack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chrizator/netattack")
    print("netattack2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chrizator/netattack2")
    print("AUXILE" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/AUXILE")
    print("hash-generator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/hash-generator")
    print("hasher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/hasher")
    print("ko-dork" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/ko-dork")
    print("OSIF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/OSIF")
    print("WifiBruteCrack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cinquemb/WifiBruteCrack")
    print("lynis" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CISOfy/lynis")
    print("rdpy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/citronneur/rdpy")
    print("commix" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/commixproject/commix")
    print("cuckoo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cuckoosandbox/cuckoo")
    print("Easymap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Easymap")
    print("Ecode" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Ecode")
    print("Hac" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Hac")
    print("sqlscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/sqlscan")
    print("shimit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cyberark/shimit")
    print("secHub" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cys3c/secHub")
    print("hammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cyweb/hammer")
    print("Kadabra" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D35m0nd142/Kadabra")
    print("LFISuite" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D35m0nd142/LFISuite")
    print("Clickjacking-Tester" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/Clickjacking-Tester")
    print("Dr0p1t-Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/Dr0p1t-Framework")
    print("elpscrk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/elpscrk")
    print("SecLists" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/danielmiessler/SecLists")
    print("dnsrecon" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/darkoperator/dnsrecon")
    print("HiddenEye-Legacy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/DarkSecDevelopers/HiddenEye-Legacy")
    print("xsser" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/epsylon/xsser")
    print("spamchat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/errorBrain/spamchat")
    print("CeWL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/digininja/CeWL")
    print("CMSmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Dionach/CMSmap")
    print("torshammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/dotfighter/torshammer")
    print("RTLSDR-Scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EarToEarOak/RTLSDR-Scanner")
    print("The-Eye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EgeBalci/The-Eye")
    print("Pybelt" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ekultek/Pybelt")
    print("multimon-ng" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EliasOenal/multimon-ng")
    print("Empire" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EmpireProject/Empire")
    print("sipvicious" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EnableSecurity/sipvicious")
    print("wafw00f" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EnableSecurity/wafw00f")
    print("BAF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/engMaher/BAF")
    print("weevely3" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/epinna/weevely3")
    print("Intersect-2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/deadbits/Intersect-2.5")
    print("wifite" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/derv82/wifite")
    print("wifite2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/derv82/wifite2")
    print("wifi-hacker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/esc0rtd3w/wifi-hacker")
    print("nodexp" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/esmog/nodexp")
    print("weeman" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/evait-security/weeman")
    print("dedsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/archival-0x/dedsploit")
    print("rang3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/floriankunushevci/rang3r")
    print("fluxion" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/FluxionNetwork/fluxion")
    print("hURL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/fnord0/hURL")
    print("EyeWitness" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/FortyNorthSecurity/EyeWitness")
    print("dnsenum" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/fwaeytens/dnsenum")
    print("msfpc" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/g0tmi1k/msfpc")
    print("hasherdotid" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/galauerscrew/hasherdotid")
    print("crowbar" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/galkan/crowbar")
    print("AstraNmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/AstraNmap")
    print("Auxscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Auxscan")
    print("Black-Hydra" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Black-Hydra")
    print("FaDe" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/FaDe")
    print("hulk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/grafov/hulk")
    print("Gemail-Hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ha3MrX/Gemail-Hack")
    print("openvas-scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/greenbone/openvas-scanner")
    print("Namechk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GONZOsint/Namechk")
    print("GoogleSearch-CLI" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/BroNils/GoogleSearch-CLI")
    print("GINF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/GINF")
    print("inther" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/inther")
    print("Lazymux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Lazymux")
    print("OWScan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/OWScan")
    print("santet-online" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/santet-online")
    print("SpazSMS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/SpazSMS")
    print("distorm" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gdabah/distorm")
    print("wifitap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GDSSecurity/wifitap")
    print("indonesian-wordlist" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/geovedi/indonesian-wordlist")
    print("dbd" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gitdurandal/dbd")
    print("Leaked" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GitHackTools/Leaked")
    print("slowloris" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gkbrk/slowloris")
    print("golismero" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/golismero/golismero")
    print("SCANNER-INURLBR" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/googleinurl/SCANNER-INURLBR")
    print("hulk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/grafov/hulk")
    print("openvas" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/greenbone/openvas")
    print("Gemail-Hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ha3MrX/Gemail-Hack")
    print("Namechk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/HA71/Namechk")
    print("webdav" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hacdias/webdav")
    print("4nonimizer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hackplayers/4nonimizer")
    print("sqliv" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/the-robot/sqliv")
    print("hashcat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hashcat/hashcat")
    print("maskprocessor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hashcat/maskprocessor")
    print("zarp" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hatRiot/zarp")
    print("Metasploit_termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/Metasploit_termux")
    print("Nethunter-In-Termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/Nethunter-In-Termux")
    print("TermuxAlpine" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/TermuxAlpine")
    print("MSF-Pg" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/haxzsadik/MSF-Pg")
    print("BinGoo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hood3dRob1n/BinGoo")
    print("Planetwork-DDOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hydra7/Planetwork-DDOS")
    print("osrframework" + Fore.RED + " -----> " + Fore.WHITE + "httos://github.com/i3visio/osrframework")
    print("angryFuzzer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ihebski/angryFuzzer")
    print("PyBozoCrack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ikkebr/PyBozoCrack")
    print("faraday" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/infobyte/faraday")
    print("plecost" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/iniqua/plecost")
    print("keimpx" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/keimpx")
    print("sslyze" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/iSECPartners/sslyze")
    print("wreckuests" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/JamesJGoodwin/wreckuests")
    print("dmitry" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jaygreig86/dmitry")
    print("peepdf" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jesparza/peepdf")
    print("cowpatty" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/joswr1ght/cowpatty")
    print("blackbox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jothatron/blackbox")
    print("Pyrit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/JPaulMora/Pyrit")
    print("GoldenEye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jseidl/GoldenEye")
    print("kickthemout" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/k4m4/kickthemout")
    print("onioff" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/k4m4/onioff")
    print("DHCPig" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kamorin/DHCPig")
    print("pybluez" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/karulis/pybluez")
    print("Remot3d" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/KeepWannabe/Remot3d")
    print("RegRipper2.8" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/keydet89/RegRipper2.8")
    print("evilginx2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kgretzky/evilginx2")
    print("txtool" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kuburan/txtool")
    print("pydictor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LandGrey/pydictor")
    print("recon-ng" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lanmaster53/recon-ng")
    print("theHarvester" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/laramies/theHarvester")
    print("httptunnel" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/larsbrinkhoff/httptunnel")
    print("InSpy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/leapsecurity/InSpy")
    print("credmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lightos/credmap")
    print("qark" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/linkedin/qark")
    print("Responder" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lgandx/Responder")
    print("wifresti" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LionSec/wifresti")
    print("xerosploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LionSec/xerosploit")
    print("Evil-create-framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LOoLzeC/Evil-create-framework")
    print("SH33LL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LOoLzeC/SH33LL")
    print("Infoga" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/Infoga")
    print("SMBrute" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/SMBrute")
    print("WAScan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/WAScan")
    print("WPSeku" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/WPSeku")
    print("xsmash" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4rktn/xsmash")
    print("zeroeye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4rktn/zeroeye")
    print("subscraper" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m8r0wn/subscraper")
    print("IPGeoLocation" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/maldevel/IPGeoLocation")
    print("Crips" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/Crips")
    print("Xshell" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/Xshell")
    print("fsociety" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/fsociety")
    print("mitmproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mitmproxy/mitmproxy")
    print("xspy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mnp/xspy")
    print("Th3inspector" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Moham3dRiahi/Th3inspector")
    print("XAttacker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Moham3dRiahi/XAttacker")
    print("apt2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/MooseDojo/apt2")
    print("sslstrip" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/moxie0/sslstrip")
    print("creddump" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/moyix/creddump")
    print("DKMC" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Mr-Un1k0d3r/DKMC")
    print("FBUPv2.0" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hendriyawan/FBUPv2.0")
    print("BadMod" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/MrSqar-Ye/BadMod")
    print("fierce" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mschwager/fierce")
    print("Stitch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nathanlopez/Stitch")
    print("demiguise" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/demiguise")
    print("Winpayloads" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/Winpayloads")
    print("termux-ubuntu" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Neo-Oli/termux-ubuntu")
    print("bbqsql" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Neohapsis/bbqsql")
    print("EggShell" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/neoneggplant/EggShell")
    print("mfcuk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nfc-tools/mfcuk")
    print("mfoc" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nfc-tools/mfoc")
    print("braa" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mteg/braa")
    print("termux-fedora" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nmilosev/termux-fedora")
    print("AutoSploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/NullArray/AutoSploit")
    print("AutoPixieWps" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nxxxu/AutoPixieWps")
    print("exploitdb" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/offensive-security/exploitdb")
    print("gobuster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OJ/gobuster")
    print("Simple-Fuzzer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/orgcandman/Simple-Fuzzer")
    print("OWASP-WebScarab" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OWASP/OWASP-WebScarab")
    print("QRLJacking" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OWASP/QRLJacking")
    print("WiFi-Pumpkin" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/P0cL4bs/WiFi-Pumpkin")
    print("Spammer-Grab" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/p4kl0nc4t/Spammer-Grab")
    print("zirikatu" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/pasahitz/zirikatu ")
    print("eternal_scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/peterpt/eternal_scanner")
    print("get" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/peterpt/get")
    print("enum4linux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/portcullislabs/enum4linux")
    print("KatanaFramework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/PowerScript/KatanaFramework")
    print("PowerSploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/PowerShellMafia/PowerSploit")
    print("proxystrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/qunxyz/proxystrike")
    print("FakeImageExploiter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/FakeImageExploiter")
    print("Meterpreter_Paranoid_Mode-SSL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL")
    print("morpheus" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/morpheus")
    print("trojanizer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/trojanizer")
    print("ExploitOnCLI" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00tmars/ExploitOnCLI")
    print("XPL-SEARCH" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00tmars/XPL-SEARCH")
    print("MyServer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rajkumrdusad/MyServer")
    print("Tool-X" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rajkumrdusad/Tool-X")
    print("ezsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/rand0m1ze/ezsploit")
    print("binwalk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ReFirmLabs/binwalk")
    print("routersploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/threat9/routersploit")
    print("shellnoob" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/reyammer/shellnoob")
    print("joomscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/rezasp/joomscan")
    print("shell-scan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rhi7/shell-scan")
    print("catphish" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ring0lab/catphish")
    print("killerbee" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/riverloopsec/killerbee")
    print("masscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/robertdavidgraham/masscan")
    print("intrace" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/robertswiecki/intrace")
    print("jsql-injection" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ron190/jsql-injection")
    print("arp-scan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/royhills/arp-scan")
    print("killchain" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ruped24/killchain")
    print("Blazy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Blazy")
    print("Hash-Buster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Hash-Buster")
    print("sqlmate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/sqlmate")
    print("Striker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Striker")
    print("XSStrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/XSStrike")
    print("EasY_HaCk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sabri-zaki/EasY_HaCk")
    print("nishang" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/samratashok/nishang")
    print("pwnat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/samyk/pwnat")
    print("kojawafft" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sandalpenyok/kojawafft")
    print("DDosy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Sanix-Darker/DDosy")
    print("fern-wifi-cracker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/savio-code/fern-wifi-cracker")
    print("ghost-phisher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/savio-code/ghost-phisher")
    print("Brutal" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Brutal")
    print("Dracnmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Dracnmap")
    print("LALIN" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/LALIN")
    print("TheFatRat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/TheFatRat")
    print("Vegile" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Vegile")
    print("the-backdoor-factory" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/secretsquirrel/the-backdoor-factory")
    print("termineter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/securestate/termineter")
    print("kwetza" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sensepost/kwetza")
    print("D-TECT-1" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shawarkhanethicalhacker/D-TECT-1")
    print("smbmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShawnDEvans/smbmap")
    print("slowhttptest" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shekyan/slowhttptest")
    print("johnny" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shinnok/johnny")
    print("HT-WPS-Breaker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SilentGhostX/HT-WPS-Breaker")
    print("PwnSTAR" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SilverFoxx/PwnSTAR")
    print("termux-wordpresscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/silverhat007/termux-wordpresscan")
    print("bulk_extractor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/simsong/bulk_extractor")
    print("uidsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/siruidops/uidsploit")
    print("fuckshitup" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Smaash/fuckshitup")
    print("snitch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Smaash/snitch")
    print("Zerodoor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Souhardya/Zerodoor")
    print("deblaze" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SpiderLabs/deblaze")
    print("jboss-autopwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SpiderLabs/jboss-autopwn")
    print("sqlmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sqlmapproject/sqlmap")
    print("termux-sudo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/st42/termux-sudo")
    print("DSSS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSSS")
    print("DSVW" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSVW")
    print("DSXS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSXS")
    print("kalibrate-rtl" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/steve-m/kalibrate-rtl")
    print("Gloom-Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/StreetSec/Gloom-Framework")
    print("nikto" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sullo/nikto")
    print("cpscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SusmithKrishnan/cpscan")
    print("torghost" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SusmithKrishnan/torghost")
    print("Wordpresscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/swisskyrepo/Wordpresscan")
    print("IP-FY" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/T4P4N/IP-FY")
    print("reaver-wps-fork-t6x" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/t6x/reaver-wps-fork-t6x")
    print("leviathan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/utkusen/leviathan")
    print("websploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/The404Hacking/websploit")
    print("hacktronian" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/thehackingsage/hacktronian")
    print("EagleEye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ThoughtfulDev/EagleEye")
    print("CHAOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tiagorlampert/CHAOS")
    print("sAINT" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tiagorlampert/sAINT")
    print("yersinia" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tomac/yersinia")
    print("ridenum" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/trustedsec/ridenum")
    print("social-engineer-toolkit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/trustedsec/social-engineer-toolkit")
    print("CMSeeK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/CMSeeK")
    print("fbvid" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/fbvid")
    print("RED_HAWK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/RED_HAWK")
    print("shellstack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/shellstack")
    print("Androspy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cyb0r9/Androspy")
    print("SocialBox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cyb0r9/SocialBox")
    print("gasmaskprint" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/twelvesec/gasmaskprint")
    print("Breacher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Breacher")
    print("Hash-Buster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Hash-Buster")
    print("ReconDog" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/ReconDog")
    print("sqlmate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/sqlmate")
    print("Striker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Striker")
    print("XSStrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/XSStrike")
    print("EvilURL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/EvilURL")
    print("GoblinWordGenerator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/GoblinWordGenerator")
    print("SocialFish" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/SocialFish")
    print("bing-ip2hosts" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/urbanadventurer/bing-ip2hosts")
    print("WhatWeb" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/urbanadventurer/WhatWeb")
    print("CredSniper" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ustayready/CredSniper")
    print("airgeddon" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/v1s1t0r1sh3r3/airgeddon")
    print("thc-ipv6" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/vanhauser-thc/thc-ipv6")
    print("sniffjoke" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/vecna/sniffjoke")
    print("termux-lazysqlmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/verluchie/termux-lazysqlmap")
    print("volatility" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/volatilityfoundation/volatility")
    print("air-hammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Wh1t3Rh1n0/air-hammer")
    print("wifiphisher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wifiphisher/wifiphisher")
    print("pixiewps" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wiire-a/pixiewps")
    print("PiDense" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/WiPi-Hunter/PiDense")
    print("doona" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wireghoul/doona")
    print("dotdotpwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wireghoul/dotdotpwn")
    print("wpscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wpscanteam/wpscan")
    print("brutespray" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/x90skysn3k/brutespray")
    print("fbi" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xHak9x/fbi")
    print("A-Rat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Xi4u7/A-Rat")
    print("wfuzz" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xmendez/wfuzz")
    print("giskismet" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xtr4nge/giskismet")
    print("Cookie-stealer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Xyl2k/Cookie-stealer")
    print("cdpsnarf" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Zapotek/cdpsnarf")
    print("zaproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zaproxy/zaproxy")
    print("koadic" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zerosum0x0/koadic")
    print("webpwn3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zigoo0/webpwn3r")
    print("\n" + "Toplam:" + Fore.YELLOW + " 364 Adet Tool İnecektir!")

else:
    print("\nHatalı Karakter Tuşladınız...")
