#!/usr/bin/env python
# -*- coding: utf-8 -*-

import webbrowser
import os 
import colorama

from colorama import Fore, Back, Style

os.system("apt-get install figlet")
os.system("clear")


print(Fore.RED + """
                                  _______          _     
                                 |__   __|        | |    
                                    | | ___   ___ | |___ 
                                    | |/ _ \ / _ \| / __|
                                    | | (_) | (_) | \___\
	  
	                            |_|\___/ \___/|_|___/ """)    

print(Fore.GREEN + """
                                     # Coded By wolkan """)


print(Fore.WHITE + """
Bu program sizlere siber güvenlikte en çok kullanılan toolları tek tuş ile indirmenizi sağlar. 
Program süresince indirilen programları kötü amaçlı kullanmayınız. Aksi takdirde kullanılması 
toplumsal ve hukuki sorumluluk doğurabilir. Olası her durumda mesuliyet ilgili kişiye aittir.""")

print(Fore.RED + """\n-----
    |
    v""")
print(Fore.WHITE + "    1. Programları İndir\n    2. İndirilecek Olan Programlar")


islem = int(input(Fore.WHITE + "\nKullanmak istediğiniz başlığın numarası: "))


if ( islem==1 ):
    	os.system("git clone https://github.com/ShuBhamg0sain/Hack_CCTV_Cam-v.3.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/trace-ip.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/SMSbomber.git")
    	os.system("git clone https://github.com/Silent-Blue/Wordlist-Creator.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/wifi-passlist.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/hack-wifi.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/reportbug.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/virous.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/Locate.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/Facebook_hack.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/rootkalilinux-termux.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/rootubantu-termux.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/termux_Arch.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/Facebook-kit.git")
    	os.system("git clone https://github.com/ShuBhamg0sain/Fbbrute.git")
    	os.system("git clone https://github.com/thewhiteh4t/seeker.git")
    	os.system("git clone https://github.com/Findomain/Findomain.git")
    	os.system("git clone https://github.com/1aN0rmus/TekDefense-Automater.git")
    	os.system("git clone https://github.com/1N3/BruteX.git")
    	os.system("git clone https://github.com/1N3/Findsploit.git")
    	os.system("git clone https://github.com/1N3/ReverseAPK.git")
    	os.system("git clone https://github.com/1N3/Sn1per.git")
    	os.system("git clone https://github.com/1tayH/noisy.git")
    	os.system("git clone https://github.com/4L13199/LITEDDOS.git")
    	os.system("git clone https://github.com/4L13199/LITESPAM.git")
    	os.system("git clone https://github.com/4shadoww/hakkuframework.git")
    	os.system("git clone https://github.com/4w4k3/BeeLogger.git")
    	os.system("git clone https://github.com/4w4k3/KnockMail.git")
    	os.system("git clone https://github.com/4w4k3/Umbrella.git")
    	os.system("git clone https://github.com/4ZM/mfterm.git")
    	os.system("git clone https://github.com/jimywork/djangohunter.git")
    	os.system("git clone https://github.com/jimywork/shodanwave.git")
    	os.system("git clone https://github.com/a0xnirudh/WebXploiter.git")
    	os.system("git clone https://github.com/abaykan/TrackOut.git")
    	os.system("git clone https://github.com/abbbe/sslcaudit.git")
    	os.system("git clone https://github.com/aboul3la/Sublist3r.git")
    	os.system("git clone https://github.com/AeonDave/doork.git")
    	os.system("git clone https://github.com/AeonDave/sir.git")
    	os.system("git clone https://github.com/anggialberto/xl-py.git")
    	os.system("git clone https://github.com/alexxy/netdiscover.git")
    	os.system("git clone https://github.com/AlisamTechnology/ATSCAN.git")
    	os.system("git clone https://github.com/almandin/fuxploider.git")
    	os.system("git clone https://github.com/abaykan/CrawlBox.git")
    	os.system("git clone https://github.com/altjx/ipwn.git")
    	os.system("git clone https://github.com/andresriancho/w3af.git")
    	os.system("git clone https://github.com/AndroBugs/AndroBugs_Framework.git")
    	os.system("git clone https://github.com/andyvaikunth/roxysploit.git")
    	os.system("git clone https://github.com/AonCyberLabs/PadBuster.git")
    	os.system("git clone https://github.com/aquynh/capstone.git")
    	os.system("git clone https://github.com/aress31/wirespy.git")
    	os.system("git clone https://github.com/arismelachroinos/lscript.git")
    	os.system("git clone https://github.com/ASHWIN990/ADB-Toolkit.git")
    	os.system("git clone https://github.com/b3-v3r/Hunner.git")
    	os.system("git clone https://github.com/BagazMukti/Termux-Styling-Shell-Script.git")
    	os.system("git clone https://github.com/bahaabdelwahed/killshot.git")
    	os.system("git clone https://github.com/bdblackhat/admin-panel-finder.git")
    	os.system("git clone https://github.com/beefproject/beef.git")
    	os.system("git clone https://github.com/behindthefirewalls/Parsero.git")
    	os.system("git clone https://github.com/bettercap/bettercap.git")
    	os.system("git clone https://github.com/bleachbit/bleachbit.git")
    	os.system("git clone https://github.com/jofpin/trape.git")
    	os.system("git clone https://github.com/byt3bl33d3r/gcat.git")
    	os.system("git clone https://github.com/bytezcrew/wfdroid-termux.git")
    	os.system("git clone https://github.com/chinoogawa/fbht.git")
    	os.system("git clone https://github.com/chrizator/netattack.git")
    	os.system("git clone https://github.com/chrizator/netattack2.git")
    	os.system("git clone https://github.com/CiKu370/AUXILE.git")
    	os.system("git clone https://github.com/CiKu370/hash-generator.git")
    	os.system("git clone https://github.com/CiKu370/hasher.git")
    	os.system("git clone https://github.com/CiKu370/ko-dork.git")
    	os.system("git clone https://github.com/CiKu370/OSIF.git")
    	os.system("git clone https://github.com/cinquemb/WifiBruteCrack.git")
    	os.system("git clone https://github.com/CISOfy/lynis.git")
    	os.system("git clone https://github.com/citronneur/rdpy.git")
    	os.system("git clone https://github.com/commixproject/commix.git")
    	os.system("git clone https://github.com/cuckoosandbox/cuckoo.git")
    	os.system("git clone https://github.com/Cvar1984/Easymap.git")
    	os.system("git clone https://github.com/Cvar1984/Ecode.git")
    	os.system("git clone https://github.com/Cvar1984/Hac.git")
    	os.system("git clone https://github.com/Cvar1984/sqlscan.git")
    	os.system("git clone https://github.com/cyberark/shimit.git")
    	os.system("git clone https://github.com/cys3c/secHub.git")
    	os.system("git clone https://github.com/cyweb/hammer.git")
    	os.system("git clone https://github.com/D35m0nd142/Kadabra.git")
    	os.system("git clone https://github.com/D35m0nd142/LFISuite.git")
    	os.system("git clone https://github.com/D4Vinci/Clickjacking-Tester.git")
    	os.system("git clone https://github.com/D4Vinci/Dr0p1t-Framework.git")
    	os.system("git clone https://github.com/D4Vinci/elpscrk.git")
    	os.system("git clone https://github.com/danielmiessler/SecLists.git")
    	os.system("git clone https://github.com/darkoperator/dnsrecon.git")
    	os.system("git clone https://github.com/DarkSecDevelopers/HiddenEye-Legacy.git")
    	os.system("git clone https://github.com/epsylon/xsser.git")
    	os.system("git clone https://github.com/errorBrain/spamchat.git")
    	os.system("git clone https://github.com/digininja/CeWL.git")
    	os.system("git clone https://github.com/Dionach/CMSmap.git")
    	os.system("git clone https://github.com/dotfighter/torshammer.git")
    	os.system("git clone https://github.com/EarToEarOak/RTLSDR-Scanner.git")
    	os.system("git clone https://github.com/EgeBalci/The-Eye.git")
    	os.system("git clone https://github.com/Ekultek/Pybelt.git")
    	os.system("git clone https://github.com/EliasOenal/multimon-ng.git")
    	os.system("git clone https://github.com/EmpireProject/Empire.git")
    	os.system("git clone https://github.com/EnableSecurity/sipvicious.git")
    	os.system("git clone https://github.com/EnableSecurity/wafw00f.git")
    	os.system("git clone https://github.com/engMaher/BAF.git")
    	os.system("git clone https://github.com/epinna/weevely3.git")
    	os.system("git clone https://github.com/deadbits/Intersect-2.5.git")
    	os.system("git clone https://github.com/derv82/wifite.git")
    	os.system("git clone https://github.com/derv82/wifite2.git")
    	os.system("git clone https://github.com/esc0rtd3w/wifi-hacker.git")
    	os.system("git clone https://github.com/esmog/nodexp.git")
    	os.system("git clone https://github.com/evait-security/weeman.git")
    	os.system("git clone https://github.com/archival-0x/dedsploit.git")
    	os.system("git clone https://github.com/floriankunushevci/rang3r.git")
    	os.system("git clone https://github.com/FluxionNetwork/fluxion.git")
    	os.system("git clone https://github.com/fnord0/hURL.git")
    	os.system("git clone https://github.com/FortyNorthSecurity/EyeWitness.git")
    	os.system("git clone https://github.com/fwaeytens/dnsenum.git")
    	os.system("git clone https://github.com/g0tmi1k/msfpc.git")
    	os.system("git clone https://github.com/galauerscrew/hasherdotid.git")
    	os.system("git clone https://github.com/galkan/crowbar.git")
    	os.system("git clone https://github.com/Gameye98/AstraNmap.git")
    	os.system("git clone https://github.com/Gameye98/Auxscan.git")
    	os.system("git clone https://github.com/Gameye98/Black-Hydra.git")
    	os.system("git clone https://github.com/Gameye98/FaDe.git")
    	os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
		os.system("git clone https://github.com/grafov/hulk.git")
		os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
		os.system("git clone https://github.com/greenbone/openvas-scanner.git")
		os.system("git clone https://github.com/GONZOsint/Namechk.git")
		os.system("git clone https://github.com/BroNils/GoogleSearch-CLI.git")
		os.system("git clone https://github.com/Gameye98/GINF.git")
		os.system("git clone https://github.com/Gameye98/inther.git")
		os.system("git clone https://github.com/Gameye98/Lazymux.git")
		os.system("git clone https://github.com/Gameye98/OWScan.git")
		os.system("git clone https://github.com/Gameye98/santet-online.git")
		os.system("git clone https://github.com/Gameye98/SpazSMS.git")
		os.system("git clone https://github.com/gdabah/distorm.git")
		os.system("git clone https://github.com/GDSSecurity/wifitap.git")
		os.system("git clone https://github.com/geovedi/indonesian-wordlist.git")
		os.system("git clone https://github.com/gitdurandal/dbd.git")
		os.system("git clone https://github.com/GitHackTools/Leaked.git")
		os.system("git clone https://github.com/gkbrk/slowloris.git")
		os.system("git clone https://github.com/golismero/golismero.git")
		os.system("git clone https://github.com/googleinurl/SCANNER-INURLBR.git")
		os.system("git clone https://github.com/grafov/hulk.git")
		os.system("git clone https://github.com/greenbone/openvas.git")
		os.system("git clone https://github.com/Ha3MrX/Gemail-Hack.git")
		os.system("git clone https://github.com/HA71/Namechk.git")
		os.system("git clone https://github.com/hacdias/webdav.git")
		os.system("git clone https://github.com/Hackplayers/4nonimizer.git")
		os.system("git clone https://github.com/the-robot/sqliv.git")
		os.system("git clone https://github.com/hashcat/hashcat.git")
		os.system("git clone https://github.com/hashcat/maskprocessor.git")
		os.system("git clone https://github.com/hatRiot/zarp.git")
		os.system("git clone https://github.com/Hax4us/Metasploit_termux.git")
		os.system("git clone https://github.com/Hax4us/Nethunter-In-Termux.git")
		os.system("git clone https://github.com/Hax4us/TermuxAlpine.git")
		os.system("git clone https://github.com/haxzsadik/MSF-Pg.git")
		os.system("git clone https://github.com/Hood3dRob1n/BinGoo.git")
		os.system("git clone https://github.com/Hydra7/Planetwork-DDOS.git")
		os.system("git clone https://github.com/i3visio/osrframework.git")
		os.system("git clone https://github.com/ihebski/angryFuzzer.git")
		os.system("git clone https://github.com/ikkebr/PyBozoCrack.git")
		os.system("git clone https://github.com/infobyte/faraday.git")
		os.system("git clone https://github.com/iniqua/plecost.git")
		os.system("git clone https://github.com/nccgroup/keimpx.git")
		os.system("git clone https://github.com/iSECPartners/sslyze.git")
		os.system("git clone https://github.com/JamesJGoodwin/wreckuests.git")
		os.system("git clone https://github.com/jaygreig86/dmitry.git")
		os.system("git clone https://github.com/jesparza/peepdf.git")
		os.system("git clone https://github.com/joswr1ght/cowpatty.git")
		os.system("git clone https://github.com/jothatron/blackbox.git")
		os.system("git clone https://github.com/JPaulMora/Pyrit.git")
		os.system("git clone https://github.com/jseidl/GoldenEye.git")
		os.system("git clone https://github.com/k4m4/kickthemout.git")
		os.system("git clone https://github.com/k4m4/onioff.git")
		os.system("git clone https://github.com/kamorin/DHCPig.git")
		os.system("git clone https://github.com/karulis/pybluez.git")
		os.system("git clone https://github.com/KeepWannabe/Remot3d.git")
		os.system("git clone https://github.com/keydet89/RegRipper2.8.git")
		os.system("git clone https://github.com/kgretzky/evilginx2.git")
		os.system("git clone https://github.com/kuburan/txtool.git")
		os.system("git clone https://github.com/LandGrey/pydictor.git")
		os.system("git clone https://github.com/lanmaster53/recon-ng.git")
		os.system("git clone https://github.com/laramies/theHarvester.git")
		os.system("git clone https://github.com/larsbrinkhoff/httptunnel.git")
		os.system("git clone https://github.com/leapsecurity/InSpy.git")
		os.system("git clone https://github.com/lgandx/Responder.git")
		os.system("git clone https://github.com/lightos/credmap.git")
		os.system("git clone https://github.com/linkedin/qark.git")
		os.system("git clone https://github.com/LionSec/wifresti.git")
		os.system("git clone https://github.com/LionSec/xerosploit.git")
		os.system("git clone https://github.com/LOoLzeC/Evil-create-framework.git")
		os.system("git clone https://github.com/LOoLzeC/SH33LL.git")
		os.system("git clone https://github.com/m4ll0k/Infoga.git")
		os.system("git clone https://github.com/m4ll0k/SMBrute.git")
		os.system("git clone https://github.com/m4ll0k/WAScan.git")
		os.system("git clone https://github.com/m4ll0k/WPSeku.git")
		os.system("git clone https://github.com/m4rktn/xsmash.git")
		os.system("git clone https://github.com/m4rktn/zeroeye.git")
		os.system("git clone https://github.com/m8r0wn/subscraper.git")
		os.system("git clone https://github.com/maldevel/IPGeoLocation.git")
		os.system("git clone https://github.com/Manisso/Crips.git")
		os.system("git clone https://github.com/Manisso/Xshell.git")
		os.system("git clone https://github.com/Manisso/fsociety.git")
		os.system("git clone https://github.com/mitmproxy/mitmproxy.git")
		os.system("git clone https://github.com/mnp/xspy.git")
		os.system("git clone https://github.com/Moham3dRiahi/Th3inspector.git")
		os.system("git clone https://github.com/Moham3dRiahi/XAttacker.git")
		os.system("git clone https://github.com/MooseDojo/apt2.git")
		os.system("git clone https://github.com/moxie0/sslstrip.git")
		os.system("git clone https://github.com/moyix/creddump.git")
		os.system("git clone https://github.com/Mr-Un1k0d3r/DKMC.git")
		os.system("git clone https://github.com/Hendriyawan/FBUPv2.0.git")
		os.system("git clone https://github.com/MrSqar-Ye/BadMod.git")
		os.system("git clone https://github.com/mschwager/fierce.git")
		os.system("git clone https://github.com/mteg/braa.git")
		os.system("git clone https://github.com/nathanlopez/Stitch.git")
		os.system("git clone https://github.com/nccgroup/demiguise.git")
		os.system("git clone https://github.com/nccgroup/Winpayloads.git")
		os.system("git clone https://github.com/Neo-Oli/termux-ubuntu.git")
		os.system("git clone https://github.com/Neohapsis/bbqsql.git")
		os.system("git clone https://github.com/neoneggplant/EggShell.git")
		os.system("git clone https://github.com/nfc-tools/mfcuk.git")
		os.system("git clone https://github.com/nfc-tools/mfoc.git")
		os.system("git clone https://github.com/nmilosev/termux-fedora.git")
		os.system("git clone https://github.com/NullArray/AutoSploit.git")
		os.system("git clone https://github.com/nxxxu/AutoPixieWps.git")
		os.system("git clone https://github.com/offensive-security/exploitdb.git")
		os.system("git clone https://github.com/OJ/gobuster.git")
		os.system("git clone https://github.com/orgcandman/Simple-Fuzzer.git")
		os.system("git clone https://github.com/OWASP/OWASP-WebScarab.git")
		os.system("git clone https://github.com/OWASP/QRLJacking.git")
		os.system("git clone https://github.com/P0cL4bs/WiFi-Pumpkin.git")
		os.system("git clone https://github.com/p4kl0nc4t/Spammer-Grab.git")
		os.system("git clone https://github.com/pasahitz/zirikatu.git")
		os.system("git clone https://github.com/peterpt/eternal_scanner.git")
		os.system("git clone https://github.com/peterpt/get.git")
		os.system("git clone https://github.com/portcullislabs/enum4linux.git")
		os.system("git clone https://github.com/PowerScript/KatanaFramework.git")
		os.system("git clone https://github.com/PowerShellMafia/PowerSploit.git")
		os.system("git clone https://github.com/qunxyz/proxystrike.git")
		os.system("git clone https://github.com/r00t-3xp10it/FakeImageExploiter.git")
		os.system("git clone https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL.git")
		os.system("git clone https://github.com/r00t-3xp10it/morpheus.git")
		os.system("git clone https://github.com/r00t-3xp10it/trojanizer.git")
		os.system("git clone https://github.com/r00tmars/ExploitOnCLI.git")
		os.system("git clone https://github.com/r00tmars/XPL-SEARCH.git")
		os.system("git clone https://github.com/Rajkumrdusad/MyServer.git")
		os.system("git clone https://github.com/Rajkumrdusad/Tool-X.git")
		os.system("git clone https://github.com/rand0m1ze/ezsploit.git")
		os.system("git clone https://github.com/ReFirmLabs/binwalk.git")
		os.system("git clone https://github.com/threat9/routersploit.git")
		os.system("git clone https://github.com/reyammer/shellnoob.git")
		os.system("git clone https://github.com/rezasp/joomscan.git")
		os.system("git clone https://github.com/Rhi7/shell-scan.git")
		os.system("git clone https://github.com/ring0lab/catphish.git")
		os.system("git clone https://github.com/riverloopsec/killerbee.git")
		os.system("git clone https://github.com/robertdavidgraham/masscan.git")
		os.system("git clone https://github.com/robertswiecki/intrace.git")
		os.system("git clone https://github.com/ron190/jsql-injection.git")
		os.system("git clone https://github.com/royhills/arp-scan.git")
		os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
		os.system("git clone https://github.com/ruped24/killchain.git")
		os.system("git clone https://github.com/s0lst1c3/eaphammer.git")
		os.system("git clone https://github.com/s0md3v/Blazy.git")
		os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
		os.system("git clone https://github.com/s0md3v/sqlmate.git")
		os.system("git clone https://github.com/s0md3v/Striker.git")
		os.system("git clone https://github.com/s0md3v/XSStrike.git")
		os.system("git clone https://github.com/sabri-zaki/EasY_HaCk.git")
		os.system("git clone https://github.com/samratashok/nishang.git")
		os.system("git clone https://github.com/samyk/pwnat.git")
		os.system("git clone https://github.com/sandalpenyok/kojawafft.git")
		os.system("git clone https://github.com/Sanix-Darker/DDosy.git")
		os.system("git clone https://github.com/savio-code/fern-wifi-cracker.git")
		os.system("git clone https://github.com/savio-code/ghost-phisher.git")
		os.system("git clone https://github.com/Screetsec/Brutal.git")
		os.system("git clone https://github.com/Screetsec/Dracnmap.git")
		os.system("git clone https://github.com/Screetsec/LALIN.git")
		os.system("git clone https://github.com/Screetsec/TheFatRat.git")
		os.system("git clone https://github.com/Screetsec/Vegile.git")
		os.system("git clone https://github.com/secretsquirrel/the-backdoor-factory.git")
		os.system("git clone https://github.com/securestate/termineter.git")
		os.system("git clone https://github.com/sensepost/kwetza.git")
		os.system("git clone https://github.com/shawarkhanethicalhacker/D-TECT-1.git")
		os.system("git clone https://github.com/ShawnDEvans/smbmap.git")
		os.system("git clone https://github.com/shekyan/slowhttptest.git")
		os.system("git clone https://github.com/shinnok/johnny.git")
		os.system("git clone https://github.com/SilentGhostX/HT-WPS-Breaker.git")
		os.system("git clone https://github.com/SilverFoxx/PwnSTAR.git")
		os.system("git clone https://github.com/silverhat007/termux-wordpresscan.git")
		os.system("git clone https://github.com/simsong/bulk_extractor.git")
		os.system("git clone https://github.com/siruidops/uidsploit.git")
		os.system("git clone https://github.com/Smaash/fuckshitup.git")
		os.system("git clone https://github.com/Smaash/snitch.git")
		os.system("git clone https://github.com/Souhardya/Zerodoor.git")
		os.system("git clone https://github.com/SpiderLabs/deblaze.git")
		os.system("git clone https://github.com/SpiderLabs/jboss-autopwn.git")
		os.system("git clone https://github.com/sqlmapproject/sqlmap.git")
		os.system("git clone https://github.com/st42/termux-sudo.git")
		os.system("git clone https://github.com/stamparm/DSSS.git")
		os.system("git clone https://github.com/stamparm/DSVW.git")
		os.system("git clone https://github.com/stamparm/DSXS.git")
		os.system("git clone https://github.com/steve-m/kalibrate-rtl.git")
		os.system("git clone https://github.com/StreetSec/Gloom-Framework.git")
		os.system("git clone https://github.com/sullo/nikto.git")
		os.system("git clone https://github.com/SusmithKrishnan/cpscan.git")
		os.system("git clone https://github.com/SusmithKrishnan/torghost.git")
		os.system("git clone https://github.com/swisskyrepo/Wordpresscan.git")
		os.system("git clone https://github.com/T4P4N/IP-FY.git")
		os.system("git clone https://github.com/t6x/reaver-wps-fork-t6x.git")
		os.system("git clone https://github.com/utkusen/leviathan.git")
		os.system("git clone https://github.com/The404Hacking/websploit.git")
		os.system("git clone https://github.com/thehackingsage/hacktronian.git")
		os.system("git clone https://github.com/ThoughtfulDev/EagleEye.git")
		os.system("git clone https://github.com/tiagorlampert/CHAOS.git")
		os.system("git clone https://github.com/tiagorlampert/sAINT.git")
		os.system("git clone https://github.com/tomac/yersinia.git")
		os.system("git clone https://github.com/trustedsec/ridenum.git")
		os.system("git clone https://github.com/trustedsec/social-engineer-toolkit.git")
		os.system("git clone https://github.com/Tuhinshubhra/CMSeeK.git")
		os.system("git clone https://github.com/Tuhinshubhra/fbvid.git")
		os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK.git")
		os.system("git clone https://github.com/Tuhinshubhra/shellstack.git")
		os.system("git clone https://github.com/Cyb0r9/Androspy.git")
		os.system("git clone https://github.com/Cyb0r9/SocialBox.git")
		os.system("git clone https://github.com/twelvesec/gasmask.git")
		os.system("git clone https://github.com/s0md3v/Breacher.git")
		os.system("git clone https://github.com/s0md3v/Hash-Buster.git")
		os.system("git clone https://github.com/s0md3v/ReconDog.git")
		os.system("git clone https://github.com/s0md3v/sqlmate.git")
		os.system("git clone https://github.com/s0md3v/Striker.git")
		os.system("git clone https://github.com/s0md3v/XSStrike.git")
		os.system("git clone https://github.com/UndeadSec/EvilURL.git")
		os.system("git clone https://github.com/UndeadSec/GoblinWordGenerator.git")
		os.system("git clone https://github.com/UndeadSec/SocialFish.git")
		os.system("git clone https://github.com/urbanadventurer/bing-ip2hosts.git")
		os.system("git clone https://github.com/urbanadventurer/WhatWeb.git")
		os.system("git clone https://github.com/ustayready/CredSniper.git")
		os.system("git clone https://github.com/v1s1t0r1sh3r3/airgeddon.git")
		os.system("git clone https://github.com/vanhauser-thc/thc-ipv6.git")
		os.system("git clone https://github.com/vecna/sniffjoke.git")
		os.system("git clone https://github.com/verluchie/termux-lazysqlmap.git")
		os.system("git clone https://github.com/volatilityfoundation/volatility.git")
		os.system("git clone https://github.com/Wh1t3Rh1n0/air-hammer.git")
		os.system("git clone https://github.com/wifiphisher/wifiphisher.git")
		os.system("git clone https://github.com/wiire-a/pixiewps.git")
		os.system("git clone https://github.com/WiPi-Hunter/PiDense.git")
		os.system("git clone https://github.com/wireghoul/doona.git")
		os.system("git clone https://github.com/wireghoul/dotdotpwn.git")
		os.system("git clone https://github.com/wpscanteam/wpscan.git")
		os.system("git clone https://github.com/x90skysn3k/brutespray.git")
		os.system("git clone https://github.com/xHak9x/fbi.git")
		os.system("git clone https://github.com/Xi4u7/A-Rat.git")
		os.system("git clone https://github.com/xmendez/wfuzz.git")
		os.system("git clone https://github.com/xtr4nge/giskismet.git")
		os.system("git clone https://github.com/Xyl2k/Cookie-stealer.git")
		os.system("git clone https://github.com/Zapotek/cdpsnarf.git")
		os.system("git clone https://github.com/zaproxy/zaproxy.git")
		os.system("git clone https://github.com/zerosum0x0/koadic.git")
		os.system("git clone https://github.com/zigoo0/webpwn3r.git")

elif (islem==2):
	print("\n" + Fore.GREEN + "zaproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zaproxy/zaproxy")
	print(Fore.GREEN + "Hack_CCTV_Cam-v.3" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain Hack_CCTV_Cam-v.3")
	print(Fore.GREEN + "trace-ip" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/trace-ip")
	print(Fore.GREEN + "SMSbomber" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/SMSbomber")
	print(Fore.GREEN + "Wordlist-Creator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Silent-Blue/Wordlist-Creator")
	print(Fore.GREEN + "wifi-passlist" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/wifi-passlist")
	print(Fore.GREEN + "hack-wifi" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/hack-wifi")
	print(Fore.GREEN + "reportbug" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/reportbug")
	print(Fore.GREEN + "virous" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/virous")
	print(Fore.GREEN + "Locate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Locate")
	print(Fore.GREEN + "Facebook_hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Facebook_hack")
	print(Fore.GREEN + "rootkalilinux-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/rootkalilinux-termux")
	print(Fore.GREEN + "rootubantu-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/rootubantu-termux")
	print(Fore.GREEN + "termux_Arch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/termux_Arch")
	print(Fore.GREEN + "Facebook-kit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Facebook-kit")
	print(Fore.GREEN + "Fbbrute" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShuBhamg0sain/Fbbrute")
	print(Fore.GREEN + "seeker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/thewhiteh4t/seeker")
	print(Fore.GREEN + "Findomain" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Findomain/Findomain")
	print(Fore.GREEN + "TekDefense-Automater" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1aN0rmus/TekDefense-Automater")
	print(Fore.GREEN + "BruteX" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/BruteX")
	print(Fore.GREEN + "Findsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/Findsploit")
	print(Fore.GREEN + "ReverseAPK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/ReverseAPK")
	print(Fore.GREEN + "Sn1per" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1N3/Sn1per")
	print(Fore.GREEN + "noisy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/1tayH/noisy")
	print(Fore.GREEN + "LITEDDOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4L13199/LITEDDOS")
	print(Fore.GREEN + "LITESPAM" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4L13199/LITESPAM")
	print(Fore.GREEN + "hakkuframework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4shadoww/hakkuframework")
	print(Fore.GREEN + "BeeLogger" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/BeeLogger")
	print(Fore.GREEN + "KnockMail" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/KnockMail")
	print(Fore.GREEN + "Umbrella" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4w4k3/Umbrella")
	print(Fore.GREEN + "mfterm" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/4ZM/mfterm")
	print(Fore.GREEN + "djangohunter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jimywork/djangohunter")
	print(Fore.GREEN + "shodanwave" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jimywork/shodanwave")
	print(Fore.GREEN + "WebXploiter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/a0xnirudh/WebXploiter")
	print(Fore.GREEN + "TrackOut" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abaykan/TrackOut")
	print(Fore.GREEN + "sslcaudit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abbbe/sslcaudit")
	print(Fore.GREEN + "Sublist3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aboul3la/Sublist3r")
	print(Fore.GREEN + "doork" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AeonDave/doork")
	print(Fore.GREEN + "sir" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AeonDave/sir")
	print(Fore.GREEN + "xl-py" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/anggialberto/xl-py")
	print(Fore.GREEN + "netdiscover" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/alexxy/netdiscover")
	print(Fore.GREEN + "ATSCAN" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AlisamTechnology/ATSCAN")
	print(Fore.GREEN + "fuxploider" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/almandin/fuxploider")
	print(Fore.GREEN + "CrawlBox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/abaykan/CrawlBox")
	print(Fore.GREEN + "ipwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/altjx/ipwn")
	print(Fore.GREEN + "avet" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/govolution/avet")
	print(Fore.GREEN + "w3af" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/andresriancho/w3af")
	print(Fore.GREEN + "AndroBugs_Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AndroBugs/AndroBugs_Framework")
	print(Fore.GREEN + "roxysploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/andyvaikunth/roxysploit")
	print(Fore.GREEN + "PadBuster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/AonCyberLabs/PadBuster")
	print(Fore.GREEN + "capstone" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aquynh/capstone")
	print(Fore.GREEN + "capstone" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/aress31/wirespy")
	print(Fore.GREEN + "lscript" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/arismelachroinos/lscript")
	print(Fore.GREEN + "ADB-Toolkit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ASHWIN990/ADB-Toolkit")
	print(Fore.GREEN + "Hunner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/b3-v3r/Hunner")
	print(Fore.GREEN + "Termux-Styling-Shell-Script" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/BagazMukti/Termux-Styling-Shell-Script")
	print(Fore.GREEN + "killshot" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bahaabdelwahed/killshot")
	print(Fore.GREEN + "admin-panel-finder" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bdblackhat/admin-panel-finder")
	print(Fore.GREEN + "beef" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/beefproject/beef")
	print(Fore.GREEN + "Parsero" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/behindthefirewalls/Parsero")
	print(Fore.GREEN + "bettercap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bettercap/bettercap")
	print(Fore.GREEN + "bleachbit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bleachbit/bleachbit")
	print(Fore.GREEN + "trape" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jofpin/trape")
	print(Fore.GREEN + "gcat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/byt3bl33d3r/gcat")
	print(Fore.GREEN + "wfdroid-termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/bytezcrew/wfdroid-termux")
	print(Fore.GREEN + "fbht" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chinoogawa/fbht")
	print(Fore.GREEN + "netattack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chrizator/netattack")
	print(Fore.GREEN + "netattack2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/chrizator/netattack2")
	print(Fore.GREEN + "AUXILE" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/AUXILE")
	print(Fore.GREEN + "hash-generator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/hash-generator")
	print(Fore.GREEN + "hasher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/hasher")
	print(Fore.GREEN + "ko-dork" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/ko-dork")
	print(Fore.GREEN + "OSIF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CiKu370/OSIF")
	print(Fore.GREEN + "WifiBruteCrack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cinquemb/WifiBruteCrack")
	print(Fore.GREEN + "lynis" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/CISOfy/lynis")
	print(Fore.GREEN + "rdpy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/citronneur/rdpy")
	print(Fore.GREEN + "commix" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/commixproject/commix")
	print(Fore.GREEN + "cuckoo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cuckoosandbox/cuckoo")
	print(Fore.GREEN + "Easymap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Easymap")
	print(Fore.GREEN + "Ecode" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Ecode")
	print(Fore.GREEN + "Hac" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/Hac")
	print(Fore.GREEN + "sqlscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cvar1984/sqlscan")
	print(Fore.GREEN + "shimit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cyberark/shimit")
	print(Fore.GREEN + "secHub" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cys3c/secHub")
	print(Fore.GREEN + "hammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/cyweb/hammer")
	print(Fore.GREEN + "Kadabra" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D35m0nd142/Kadabra")
	print(Fore.GREEN + "LFISuite" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D35m0nd142/LFISuite")
	print(Fore.GREEN + "Clickjacking-Tester" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/Clickjacking-Tester")
	print(Fore.GREEN + "Dr0p1t-Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/Dr0p1t-Framework")
	print(Fore.GREEN + "elpscrk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/D4Vinci/elpscrk")
	print(Fore.GREEN + "SecLists" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/danielmiessler/SecLists")
	print(Fore.GREEN + "dnsrecon" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/darkoperator/dnsrecon")
	print(Fore.GREEN + "HiddenEye-Legacy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/DarkSecDevelopers/HiddenEye-Legacy")
	print(Fore.GREEN + "xsser" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/epsylon/xsser")
	print(Fore.GREEN + "spamchat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/errorBrain/spamchat")
	print(Fore.GREEN + "CeWL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/digininja/CeWL")
	print(Fore.GREEN + "CMSmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Dionach/CMSmap")
	print(Fore.GREEN + "torshammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/dotfighter/torshammer")
	print(Fore.GREEN + "RTLSDR-Scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EarToEarOak/RTLSDR-Scanner")
	print(Fore.GREEN + "The-Eye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EgeBalci/The-Eye")
	print(Fore.GREEN + "Pybelt" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ekultek/Pybelt")
	print(Fore.GREEN + "multimon-ng" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EliasOenal/multimon-ng")
	print(Fore.GREEN + "Empire" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EmpireProject/Empire")
	print(Fore.GREEN + "sipvicious" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EnableSecurity/sipvicious")
	print(Fore.GREEN + "wafw00f" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/EnableSecurity/wafw00f")
	print(Fore.GREEN + "BAF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/engMaher/BAF")
	print(Fore.GREEN + "weevely3" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/epinna/weevely3")
	print(Fore.GREEN + "Intersect-2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/deadbits/Intersect-2.5")
	print(Fore.GREEN + "wifite" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/derv82/wifite")
	print(Fore.GREEN + "wifite2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/derv82/wifite2")
	print(Fore.GREEN + "wifi-hacker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/esc0rtd3w/wifi-hacker")
	print(Fore.GREEN + "nodexp" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/esmog/nodexp")
	print(Fore.GREEN + "weeman" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/evait-security/weeman")
	print(Fore.GREEN + "dedsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/archival-0x/dedsploit")
	print(Fore.GREEN + "rang3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/floriankunushevci/rang3r")
	print(Fore.GREEN + "fluxion" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/FluxionNetwork/fluxion")
	print(Fore.GREEN + "hURL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/fnord0/hURL")
	print(Fore.GREEN + "EyeWitness" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/FortyNorthSecurity/EyeWitness")
	print(Fore.GREEN + "dnsenum" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/fwaeytens/dnsenum")
	print(Fore.GREEN + "msfpc" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/g0tmi1k/msfpc")
	print(Fore.GREEN + "hasherdotid" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/galauerscrew/hasherdotid")
	print(Fore.GREEN + "crowbar" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/galkan/crowbar")
	print(Fore.GREEN + "AstraNmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/AstraNmap")
	print(Fore.GREEN + "Auxscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Auxscan")
	print(Fore.GREEN + "Black-Hydra" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Black-Hydra")
	print(Fore.GREEN + "FaDe" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/FaDe")
	print(Fore.GREEN + "hulk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/grafov/hulk")
	print(Fore.GREEN + "Gemail-Hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ha3MrX/Gemail-Hack")
	print(Fore.GREEN + "openvas-scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/greenbone/openvas-scanner")
	print(Fore.GREEN + "Namechk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GONZOsint/Namechk")
	print(Fore.GREEN + "GoogleSearch-CLI" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/BroNils/GoogleSearch-CLI")
	print(Fore.GREEN + "GINF" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/GINF")
	print(Fore.GREEN + "inther" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/inther")
	print(Fore.GREEN + "Lazymux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/Lazymux")
	print(Fore.GREEN + "OWScan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/OWScan")
	print(Fore.GREEN + "santet-online" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/santet-online")
	print(Fore.GREEN + "SpazSMS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Gameye98/SpazSMS")
	print(Fore.GREEN + "distorm" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gdabah/distorm")
	print(Fore.GREEN + "wifitap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GDSSecurity/wifitap")
	print(Fore.GREEN + "indonesian-wordlist" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/geovedi/indonesian-wordlist")
	print(Fore.GREEN + "dbd" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gitdurandal/dbd")
	print(Fore.GREEN + "Leaked" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/GitHackTools/Leaked")
	print(Fore.GREEN + "slowloris" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/gkbrk/slowloris")
	print(Fore.GREEN + "golismero" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/golismero/golismero")
	print(Fore.GREEN + "SCANNER-INURLBR" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/googleinurl/SCANNER-INURLBR")
	print(Fore.GREEN + "hulk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/grafov/hulk")
	print(Fore.GREEN + "openvas" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/greenbone/openvas")
	print(Fore.GREEN + "Gemail-Hack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Ha3MrX/Gemail-Hack")
	print(Fore.GREEN + "Namechk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/HA71/Namechk")
	print(Fore.GREEN + "webdav" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hacdias/webdav")
	print(Fore.GREEN + "4nonimizer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hackplayers/4nonimizer")
	print(Fore.GREEN + "sqliv" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/the-robot/sqliv")
	print(Fore.GREEN + "hashcat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hashcat/hashcat")
	print(Fore.GREEN + "maskprocessor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hashcat/maskprocessor")
	print(Fore.GREEN + "zarp" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/hatRiot/zarp")
	print(Fore.GREEN + "Metasploit_termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/Metasploit_termux")
	print(Fore.GREEN + "Nethunter-In-Termux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/Nethunter-In-Termux")
	print(Fore.GREEN + "TermuxAlpine" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hax4us/TermuxAlpine")
	print(Fore.GREEN + "MSF-Pg" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/haxzsadik/MSF-Pg")
	print(Fore.GREEN + "BinGoo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hood3dRob1n/BinGoo")
	print(Fore.GREEN + "Planetwork-DDOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hydra7/Planetwork-DDOS")
	print(Fore.GREEN + "osrframework" + Fore.RED + " -----> " + Fore.WHITE + "httos://github.com/i3visio/osrframework")
	print(Fore.GREEN + "angryFuzzer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ihebski/angryFuzzer")
	print(Fore.GREEN + "PyBozoCrack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ikkebr/PyBozoCrack")
	print(Fore.GREEN + "faraday" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/infobyte/faraday")
	print(Fore.GREEN + "plecost" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/iniqua/plecost")
	print(Fore.GREEN + "keimpx" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/keimpx")
	print(Fore.GREEN + "sslyze" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/iSECPartners/sslyze")
	print(Fore.GREEN + "wreckuests" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/JamesJGoodwin/wreckuests")
	print(Fore.GREEN + "dmitry" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jaygreig86/dmitry")
	print(Fore.GREEN + "peepdf" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jesparza/peepdf")
	print(Fore.GREEN + "cowpatty" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/joswr1ght/cowpatty")
    	print(Fore.GREEN + "blackbox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jothatron/blackbox")
	print(Fore.GREEN + "Pyrit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/JPaulMora/Pyrit")
	print(Fore.GREEN + "GoldenEye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/jseidl/GoldenEye")
	print(Fore.GREEN + "kickthemout" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/k4m4/kickthemout")
	print(Fore.GREEN + "onioff" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/k4m4/onioff")
	print(Fore.GREEN + "DHCPig" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kamorin/DHCPig")
	print(Fore.GREEN + "pybluez" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/karulis/pybluez")
	print(Fore.GREEN + "Remot3d" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/KeepWannabe/Remot3d")
	print(Fore.GREEN + "RegRipper2.8" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/keydet89/RegRipper2.8")
	print(Fore.GREEN + "evilginx2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kgretzky/evilginx2")
	print(Fore.GREEN + "txtool" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/kuburan/txtool")
	print(Fore.GREEN + "pydictor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LandGrey/pydictor")
	print(Fore.GREEN + "recon-ng" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lanmaster53/recon-ng")
	print(Fore.GREEN + "theHarvester" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/laramies/theHarvester")
	print(Fore.GREEN + "httptunnel" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/larsbrinkhoff/httptunnel")
	print(Fore.GREEN + "InSpy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/leapsecurity/InSpy")
	print(Fore.GREEN + "credmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lightos/credmap")
	print(Fore.GREEN + "qark" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/linkedin/qark")
	print(Fore.GREEN + "Responder" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/lgandx/Responder")
	print(Fore.GREEN + "wifresti" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LionSec/wifresti")
	print(Fore.GREEN + "xerosploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LionSec/xerosploit")
	print(Fore.GREEN + "Evil-create-framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LOoLzeC/Evil-create-framework")
	print(Fore.GREEN + "SH33LL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/LOoLzeC/SH33LL")
	print(Fore.GREEN + "Infoga" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/Infoga")
	print(Fore.GREEN + "SMBrute" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/SMBrute")
	print(Fore.GREEN + "WAScan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/WAScan")
	print(Fore.GREEN + "WPSeku" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4ll0k/WPSeku")
	print(Fore.GREEN + "xsmash" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4rktn/xsmash")
	print(Fore.GREEN + "zeroeye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m4rktn/zeroeye")
	print(Fore.GREEN + "subscraper" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/m8r0wn/subscraper")
	print(Fore.GREEN + "IPGeoLocation" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/maldevel/IPGeoLocation")
	print(Fore.GREEN + "Crips" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/Crips")
	print(Fore.GREEN + "Xshell" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/Xshell")
	print(Fore.GREEN + "fsociety" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Manisso/fsociety")
	print(Fore.GREEN + "mitmproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mitmproxy/mitmproxy")
	print(Fore.GREEN + "xspy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mnp/xspy")
	print(Fore.GREEN + "Th3inspector" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Moham3dRiahi/Th3inspector")
	print(Fore.GREEN + "XAttacker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Moham3dRiahi/XAttacker")
	print(Fore.GREEN + "apt2" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/MooseDojo/apt2")
	print(Fore.GREEN + "sslstrip" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/moxie0/sslstrip")
	print(Fore.GREEN + "creddump" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/moyix/creddump")
	print(Fore.GREEN + "DKMC" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Mr-Un1k0d3r/DKMC")
	print(Fore.GREEN + "FBUPv2.0" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Hendriyawan/FBUPv2.0")
	print(Fore.GREEN + "BadMod" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/MrSqar-Ye/BadMod")
	print(Fore.GREEN + "fierce" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mschwager/fierce")
	print(Fore.GREEN + "Stitch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nathanlopez/Stitch")
	print(Fore.GREEN + "demiguise" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/demiguise")
	print(Fore.GREEN + "Winpayloads" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nccgroup/Winpayloads")
	print(Fore.GREEN + "termux-ubuntu" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Neo-Oli/termux-ubuntu")
	print(Fore.GREEN + "bbqsql" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Neohapsis/bbqsql")
	print(Fore.GREEN + "EggShell" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/neoneggplant/EggShell")
	print(Fore.GREEN + "mfcuk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nfc-tools/mfcuk")
	print(Fore.GREEN + "mfoc" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nfc-tools/mfoc")
	print(Fore.GREEN + "braa" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/mteg/braa")
	print(Fore.GREEN + "termux-fedora" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nmilosev/termux-fedora")
	print(Fore.GREEN + "AutoSploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/NullArray/AutoSploit")
	print(Fore.GREEN + "AutoPixieWps" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/nxxxu/AutoPixieWps")
	print(Fore.GREEN + "exploitdb" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/offensive-security/exploitdb")
	print(Fore.GREEN + "gobuster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OJ/gobuster")
	print(Fore.GREEN + "Simple-Fuzzer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/orgcandman/Simple-Fuzzer")
	print(Fore.GREEN + "OWASP-WebScarab" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OWASP/OWASP-WebScarab")
	print(Fore.GREEN + "QRLJacking" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/OWASP/QRLJacking")
	print(Fore.GREEN + "WiFi-Pumpkin" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/P0cL4bs/WiFi-Pumpkin")
	print(Fore.GREEN + "Spammer-Grab" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/p4kl0nc4t/Spammer-Grab")
	print(Fore.GREEN + "zirikatu" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/pasahitz/zirikatu ")
	print(Fore.GREEN + "eternal_scanner" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/peterpt/eternal_scanner")
	print(Fore.GREEN + "get" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/peterpt/get")
	print(Fore.GREEN + "enum4linux" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/portcullislabs/enum4linux")
	print(Fore.GREEN + "KatanaFramework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/PowerScript/KatanaFramework")
	print(Fore.GREEN + "PowerSploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/PowerShellMafia/PowerSploit")
	print(Fore.GREEN + "proxystrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/qunxyz/proxystrike")
	print(Fore.GREEN + "FakeImageExploiter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/FakeImageExploiter")
	print(Fore.GREEN + "Meterpreter_Paranoid_Mode-SSL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/Meterpreter_Paranoid_Mode-SSL")
	print(Fore.GREEN + "morpheus" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/morpheus")
	print(Fore.GREEN + "trojanizer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00t-3xp10it/trojanizer")
	print(Fore.GREEN + "ExploitOnCLI" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00tmars/ExploitOnCLI")
	print(Fore.GREEN + "XPL-SEARCH" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/r00tmars/XPL-SEARCH")
	print(Fore.GREEN + "MyServer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rajkumrdusad/MyServer")
	print(Fore.GREEN + "Tool-X" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rajkumrdusad/Tool-X")
	print(Fore.GREEN + "ezsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/rand0m1ze/ezsploit")
	print(Fore.GREEN + "binwalk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ReFirmLabs/binwalk")
	print(Fore.GREEN + "routersploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/threat9/routersploit")
	print(Fore.GREEN + "shellnoob" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/reyammer/shellnoob")
	print(Fore.GREEN + "joomscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/rezasp/joomscan")
	print(Fore.GREEN + "shell-scan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Rhi7/shell-scan")
	print(Fore.GREEN + "catphish" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ring0lab/catphish")
	print(Fore.GREEN + "killerbee" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/riverloopsec/killerbee")
	print(Fore.GREEN + "masscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/robertdavidgraham/masscan")
	print(Fore.GREEN + "intrace" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/robertswiecki/intrace")
	print(Fore.GREEN + "jsql-injection" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ron190/jsql-injection")
	print(Fore.GREEN + "arp-scan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/royhills/arp-scan")
	print(Fore.GREEN + "killchain" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ruped24/killchain")
	print(Fore.GREEN + "Blazy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Blazy")
	print(Fore.GREEN + "Hash-Buster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Hash-Buster")
	print(Fore.GREEN + "sqlmate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/sqlmate")
	print(Fore.GREEN + "Striker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Striker")
	print(Fore.GREEN + "XSStrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/XSStrike")
	print(Fore.GREEN + "EasY_HaCk" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sabri-zaki/EasY_HaCk")
	print(Fore.GREEN + "nishang" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/samratashok/nishang")
	print(Fore.GREEN + "pwnat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/samyk/pwnat")
	print(Fore.GREEN + "kojawafft" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sandalpenyok/kojawafft")
	print(Fore.GREEN + "DDosy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Sanix-Darker/DDosy")
	print(Fore.GREEN + "fern-wifi-cracker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/savio-code/fern-wifi-cracker")
	print(Fore.GREEN + "ghost-phisher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/savio-code/ghost-phisher")
	print(Fore.GREEN + "Brutal" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Brutal")
	print(Fore.GREEN + "Dracnmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Dracnmap")
	print(Fore.GREEN + "LALIN" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/LALIN")
	print(Fore.GREEN + "TheFatRat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/TheFatRat")
	print(Fore.GREEN + "Vegile" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Screetsec/Vegile")
	print(Fore.GREEN + "the-backdoor-factory" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/secretsquirrel/the-backdoor-factory")
	print(Fore.GREEN + "termineter" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/securestate/termineter")
	print(Fore.GREEN + "kwetza" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sensepost/kwetza")
	print(Fore.GREEN + "D-TECT-1" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shawarkhanethicalhacker/D-TECT-1")
	print(Fore.GREEN + "smbmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ShawnDEvans/smbmap")
	print(Fore.GREEN + "slowhttptest" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shekyan/slowhttptest")
	print(Fore.GREEN + "johnny" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/shinnok/johnny")
	print(Fore.GREEN + "HT-WPS-Breaker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SilentGhostX/HT-WPS-Breaker")
	print(Fore.GREEN + "PwnSTAR" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SilverFoxx/PwnSTAR")
	print(Fore.GREEN + "termux-wordpresscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/silverhat007/termux-wordpresscan")
	print(Fore.GREEN + "bulk_extractor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/simsong/bulk_extractor")
	print(Fore.GREEN + "uidsploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/siruidops/uidsploit")
	print(Fore.GREEN + "fuckshitup" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Smaash/fuckshitup")
	print(Fore.GREEN + "snitch" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Smaash/snitch")
	print(Fore.GREEN + "Zerodoor" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Souhardya/Zerodoor")
	print(Fore.GREEN + "deblaze" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SpiderLabs/deblaze")
	print(Fore.GREEN + "jboss-autopwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SpiderLabs/jboss-autopwn")
	print(Fore.GREEN + "sqlmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sqlmapproject/sqlmap")
	print(Fore.GREEN + "termux-sudo" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/st42/termux-sudo")
	print(Fore.GREEN + "DSSS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSSS")
	print(Fore.GREEN + "DSVW" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSVW")
	print(Fore.GREEN + "DSXS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/stamparm/DSXS")
	print(Fore.GREEN + "kalibrate-rtl" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/steve-m/kalibrate-rtl")
	print(Fore.GREEN + "Gloom-Framework" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/StreetSec/Gloom-Framework")
	print(Fore.GREEN + "nikto" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/sullo/nikto")
	print(Fore.GREEN + "cpscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SusmithKrishnan/cpscan")
	print(Fore.GREEN + "torghost" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/SusmithKrishnan/torghost")
	print(Fore.GREEN + "Wordpresscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/swisskyrepo/Wordpresscan")
	print(Fore.GREEN + "IP-FY" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/T4P4N/IP-FY")
	print(Fore.GREEN + "reaver-wps-fork-t6x" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/t6x/reaver-wps-fork-t6x")
	print(Fore.GREEN + "leviathan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/utkusen/leviathan")
	print(Fore.GREEN + "websploit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/The404Hacking/websploit")
	print(Fore.GREEN + "hacktronian" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/thehackingsage/hacktronian")
	print(Fore.GREEN + "EagleEye" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ThoughtfulDev/EagleEye")
	print(Fore.GREEN + "CHAOS" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tiagorlampert/CHAOS")
	print(Fore.GREEN + "sAINT" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tiagorlampert/sAINT")
	print(Fore.GREEN + "yersinia" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/tomac/yersinia")
	print(Fore.GREEN + "ridenum" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/trustedsec/ridenum")
	print(Fore.GREEN + "social-engineer-toolkit" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/trustedsec/social-engineer-toolkit")
	print(Fore.GREEN + "CMSeeK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/CMSeeK")
	print(Fore.GREEN + "fbvid" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/fbvid")
	print(Fore.GREEN + "RED_HAWK" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/RED_HAWK")
	print(Fore.GREEN + "shellstack" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Tuhinshubhra/shellstack")
	print(Fore.GREEN + "Androspy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cyb0r9/Androspy")
	print(Fore.GREEN + "SocialBox" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Cyb0r9/SocialBox")
	print(Fore.GREEN + "gasmaskprint" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/twelvesec/gasmaskprint")
	print(Fore.GREEN + "Breacher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Breacher")
	print(Fore.GREEN + "Hash-Buster" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Hash-Buster")
	print(Fore.GREEN + "ReconDog" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/ReconDog")
	print(Fore.GREEN + "sqlmate" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/sqlmate")
	print(Fore.GREEN + "Striker" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/Striker")
	print(Fore.GREEN + "XSStrike" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/s0md3v/XSStrike")
	print(Fore.GREEN + "EvilURL" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/EvilURL")
	print(Fore.GREEN + "GoblinWordGenerator" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/GoblinWordGenerator")
	print(Fore.GREEN + "SocialFish" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/UndeadSec/SocialFish")
	print(Fore.GREEN + "bing-ip2hosts" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/urbanadventurer/bing-ip2hosts")
	print(Fore.GREEN + "WhatWeb" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/urbanadventurer/WhatWeb")
	print(Fore.GREEN + "CredSniper" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/ustayready/CredSniper")
	print(Fore.GREEN + "airgeddon" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/v1s1t0r1sh3r3/airgeddon")
	print(Fore.GREEN + "thc-ipv6" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/vanhauser-thc/thc-ipv6")
	print(Fore.GREEN + "sniffjoke" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/vecna/sniffjoke")
	print(Fore.GREEN + "termux-lazysqlmap" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/verluchie/termux-lazysqlmap")
	print(Fore.GREEN + "volatility" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/volatilityfoundation/volatility")
	print(Fore.GREEN + "air-hammer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Wh1t3Rh1n0/air-hammer")
	print(Fore.GREEN + "wifiphisher" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wifiphisher/wifiphisher")
	print(Fore.GREEN + "pixiewps" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wiire-a/pixiewps")
	print(Fore.GREEN + "PiDense" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/WiPi-Hunter/PiDense")
	print(Fore.GREEN + "doona" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wireghoul/doona")
	print(Fore.GREEN + "dotdotpwn" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wireghoul/dotdotpwn")
	print(Fore.GREEN + "wpscan" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/wpscanteam/wpscan")
	print(Fore.GREEN + "brutespray" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/x90skysn3k/brutespray")
	print(Fore.GREEN + "fbi" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xHak9x/fbi")
	print(Fore.GREEN + "A-Rat" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Xi4u7/A-Rat")
	print(Fore.GREEN + "wfuzz" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xmendez/wfuzz")
	print(Fore.GREEN + "giskismet" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/xtr4nge/giskismet")
	print(Fore.GREEN + "Cookie-stealer" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Xyl2k/Cookie-stealer")
	print(Fore.GREEN + "cdpsnarf" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/Zapotek/cdpsnarf")
	print(Fore.GREEN + "zaproxy" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zaproxy/zaproxy")
	print(Fore.GREEN + "koadic" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zerosum0x0/koadic")
	print(Fore.GREEN + "webpwn3r" + Fore.RED + " -----> " + Fore.WHITE + "https://github.com/zigoo0/webpwn3r")
	print("\n" + Fore.GREEN + "Toplam:" + Fore.YELLOW + " 364 Adet Tool İnecektir!")

else:
	print("\nHatalı Karakter Tuşladınız...")
